/*
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.2.1
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ezmax.api;

import eZmaxAPI.ApiException;
import com.ezmax.api.model.AttachmentGetAttachmentlogsV1Response;
import com.ezmax.api.model.CommonResponseError;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ObjectAttachmentApi
 */
@Disabled
public class ObjectAttachmentApiTest {

    private final ObjectAttachmentApi api = new ObjectAttachmentApi();

    /**
     * Retrieve the content
     *
     * Using this endpoint, you can retrieve the content of an attachment.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void attachmentDownloadV1Test() throws ApiException {
        Integer pkiAttachmentID = null;
        api.attachmentDownloadV1(pkiAttachmentID);
        // TODO: test validations
    }

    /**
     * Retrieve the Attachmentlogs
     *
     * Using this endpoint, you can retrieve the Attachmentlogs of an attachment.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void attachmentGetAttachmentlogsV1Test() throws ApiException {
        Integer pkiAttachmentID = null;
        AttachmentGetAttachmentlogsV1Response response = api.attachmentGetAttachmentlogsV1(pkiAttachmentID);
        // TODO: test validations
    }

}
