/*
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.2.1
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ezmax.api;

import eZmaxAPI.ApiException;
import com.ezmax.api.model.FranchisereferalincomeCreateObjectV2Request;
import com.ezmax.api.model.FranchisereferalincomeCreateObjectV2Response;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ObjectFranchisereferalincomeApi
 */
@Disabled
public class ObjectFranchisereferalincomeApiTest {

    private final ObjectFranchisereferalincomeApi api = new ObjectFranchisereferalincomeApi();

    /**
     * Create a new Franchisereferalincome
     *
     * The endpoint allows to create one or many elements at once.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void franchisereferalincomeCreateObjectV2Test() throws ApiException {
        FranchisereferalincomeCreateObjectV2Request franchisereferalincomeCreateObjectV2Request = null;
        FranchisereferalincomeCreateObjectV2Response response = api.franchisereferalincomeCreateObjectV2(franchisereferalincomeCreateObjectV2Request);
        // TODO: test validations
    }

}
