/*
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.2.1
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ezmax.api.model;

import java.util.Objects;
import com.ezmax.api.model.AttachmentResponse;
import com.ezmax.api.model.CommonAudit;
import com.ezmax.api.model.FieldEAttachmentDocumenttype;
import com.ezmax.api.model.FieldEAttachmentPrivacy;
import com.ezmax.api.model.FieldEAttachmentType;
import com.ezmax.api.model.FieldEAttachmentVerified;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import eZmaxAPI.JSON;

/**
 * A Attachment Object
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-01-17T15:03:32.455495633Z[Etc/UTC]", comments = "Generator version: 7.10.0")
public class AttachmentResponseCompound extends AttachmentResponse {
  public AttachmentResponseCompound() {
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    return super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(super.hashCode());
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AttachmentResponseCompound {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("pkiAttachmentID");
    openapiFields.add("fkiComputerID");
    openapiFields.add("fkiAdjustmentID");
    openapiFields.add("fkiAgentID");
    openapiFields.add("fkiBankaccountID");
    openapiFields.add("fkiBrokerID");
    openapiFields.add("fkiCommissionadvanceID");
    openapiFields.add("fkiCommunicationID");
    openapiFields.add("fkiCustomerID");
    openapiFields.add("fkiCustomertemplateID");
    openapiFields.add("fkiDepositID");
    openapiFields.add("fkiDeposittransitchequeID");
    openapiFields.add("fkiElectronicfundstransferID");
    openapiFields.add("fkiEmployeeID");
    openapiFields.add("fkiExternalbrokerID");
    openapiFields.add("fkiEzcomadvanceserverID");
    openapiFields.add("fkiEzcomcompanyID");
    openapiFields.add("fkiEzsigndocumentID");
    openapiFields.add("fkiGhacqcontractID");
    openapiFields.add("fkiInscriptionID");
    openapiFields.add("fkiInscriptiontempID");
    openapiFields.add("fkiInscriptionnotauthenticatedID");
    openapiFields.add("fkiInvoiceID");
    openapiFields.add("fkiBuyercontractID");
    openapiFields.add("fkiFranchisebrokerID");
    openapiFields.add("fkiFranchiseagenceID");
    openapiFields.add("fkiFranchiseofficeID");
    openapiFields.add("fkiFranchisefranchiseID");
    openapiFields.add("fkiFranchisecomplaintID");
    openapiFields.add("fkiLeadID");
    openapiFields.add("fkiMarketingprogramID");
    openapiFields.add("fkiMarketingfollowID");
    openapiFields.add("fkiNotaryID");
    openapiFields.add("fkiOfficetaxreportID");
    openapiFields.add("fkiOtherincomeID");
    openapiFields.add("fkiPaymentpreparationID");
    openapiFields.add("fkiPurchaseID");
    openapiFields.add("fkiSalaryID");
    openapiFields.add("fkiSupplierID");
    openapiFields.add("fkiTranqcontractID");
    openapiFields.add("fkiTemplateID");
    openapiFields.add("fkiInscriptionchecklistID");
    openapiFields.add("fkiFolderID");
    openapiFields.add("fkiRejectedoffertopurchaseID");
    openapiFields.add("fkiDisclosureID");
    openapiFields.add("fkiReconciliationID");
    openapiFields.add("fkiEzsigndocumentIDReference");
    openapiFields.add("eAttachmentDocumenttype");
    openapiFields.add("sAttachmentName");
    openapiFields.add("eAttachmentPrivacy");
    openapiFields.add("fkiUserIDSpecific");
    openapiFields.add("eAttachmentType");
    openapiFields.add("iAttachmentSize");
    openapiFields.add("iAttachmentEDMmoduleflag");
    openapiFields.add("sAttachmentMD5");
    openapiFields.add("bAttachmentDeleted");
    openapiFields.add("bAttachmentValid");
    openapiFields.add("eAttachmentVerified");
    openapiFields.add("tAttachmentRejectioncomment");
    openapiFields.add("fkiUserIDOwner");
    openapiFields.add("objAudit");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("pkiAttachmentID");
    openapiRequiredFields.add("eAttachmentDocumenttype");
    openapiRequiredFields.add("sAttachmentName");
    openapiRequiredFields.add("eAttachmentPrivacy");
    openapiRequiredFields.add("eAttachmentType");
    openapiRequiredFields.add("iAttachmentSize");
    openapiRequiredFields.add("sAttachmentMD5");
    openapiRequiredFields.add("bAttachmentDeleted");
    openapiRequiredFields.add("bAttachmentValid");
    openapiRequiredFields.add("eAttachmentVerified");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to AttachmentResponseCompound
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!AttachmentResponseCompound.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in AttachmentResponseCompound is not found in the empty JSON string", AttachmentResponseCompound.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!AttachmentResponseCompound.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `AttachmentResponseCompound` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : AttachmentResponseCompound.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!AttachmentResponseCompound.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'AttachmentResponseCompound' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<AttachmentResponseCompound> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(AttachmentResponseCompound.class));

       return (TypeAdapter<T>) new TypeAdapter<AttachmentResponseCompound>() {
           @Override
           public void write(JsonWriter out, AttachmentResponseCompound value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public AttachmentResponseCompound read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of AttachmentResponseCompound given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of AttachmentResponseCompound
   * @throws IOException if the JSON string is invalid with respect to AttachmentResponseCompound
   */
  public static AttachmentResponseCompound fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, AttachmentResponseCompound.class);
  }

  /**
   * Convert an instance of AttachmentResponseCompound to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

