/*
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ezmax.api.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import eZmaxAPI.JSON;

/**
 * Definition of objSQLQuery Object
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-10-05T13:57:46.112747798Z[Etc/UTC]")
public class CommonResponseObjSQLQuery {
  public static final String SERIALIZED_NAME_S_QUERY = "sQuery";
  @SerializedName(SERIALIZED_NAME_S_QUERY)
  private String sQuery;

  public static final String SERIALIZED_NAME_F_DURATION = "fDuration";
  @SerializedName(SERIALIZED_NAME_F_DURATION)
  private Float fDuration;

  public CommonResponseObjSQLQuery() {
  }

  public CommonResponseObjSQLQuery sQuery(String sQuery) {
    
    this.sQuery = sQuery;
    return this;
  }

   /**
   * The SQL Query
   * @return sQuery
  **/
  @javax.annotation.Nonnull
  public String getsQuery() {
    return sQuery;
  }


  public void setsQuery(String sQuery) {
    this.sQuery = sQuery;
  }


  public CommonResponseObjSQLQuery fDuration(Float fDuration) {
    
    this.fDuration = fDuration;
    return this;
  }

   /**
   * Execution time of the SQL Query in seconds
   * @return fDuration
  **/
  @javax.annotation.Nonnull
  public Float getfDuration() {
    return fDuration;
  }


  public void setfDuration(Float fDuration) {
    this.fDuration = fDuration;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CommonResponseObjSQLQuery commonResponseObjSQLQuery = (CommonResponseObjSQLQuery) o;
    return Objects.equals(this.sQuery, commonResponseObjSQLQuery.sQuery) &&
        Objects.equals(this.fDuration, commonResponseObjSQLQuery.fDuration);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sQuery, fDuration);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CommonResponseObjSQLQuery {\n");
    sb.append("    sQuery: ").append(toIndentedString(sQuery)).append("\n");
    sb.append("    fDuration: ").append(toIndentedString(fDuration)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("sQuery");
    openapiFields.add("fDuration");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("sQuery");
    openapiRequiredFields.add("fDuration");
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to CommonResponseObjSQLQuery
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!CommonResponseObjSQLQuery.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in CommonResponseObjSQLQuery is not found in the empty JSON string", CommonResponseObjSQLQuery.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!CommonResponseObjSQLQuery.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `CommonResponseObjSQLQuery` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : CommonResponseObjSQLQuery.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("sQuery").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `sQuery` to be a primitive type in the JSON string but got `%s`", jsonObj.get("sQuery").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CommonResponseObjSQLQuery.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CommonResponseObjSQLQuery' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CommonResponseObjSQLQuery> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CommonResponseObjSQLQuery.class));

       return (TypeAdapter<T>) new TypeAdapter<CommonResponseObjSQLQuery>() {
           @Override
           public void write(JsonWriter out, CommonResponseObjSQLQuery value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CommonResponseObjSQLQuery read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of CommonResponseObjSQLQuery given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of CommonResponseObjSQLQuery
  * @throws IOException if the JSON string is invalid with respect to CommonResponseObjSQLQuery
  */
  public static CommonResponseObjSQLQuery fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CommonResponseObjSQLQuery.class);
  }

 /**
  * Convert an instance of CommonResponseObjSQLQuery to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

