/*
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ezmax.api.model;

import java.util.Objects;
import com.ezmax.api.model.CustomFormDataDocumentResponse;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import eZmaxAPI.JSON;

/**
 * A forms Data Folder Object
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-09-25T00:08:36.313533228Z[Etc/UTC]")
public class CustomFormsDataFolderResponse {
  public static final String SERIALIZED_NAME_PKI_EZSIGNFOLDER_I_D = "pkiEzsignfolderID";
  @SerializedName(SERIALIZED_NAME_PKI_EZSIGNFOLDER_I_D)
  private Integer pkiEzsignfolderID;

  public static final String SERIALIZED_NAME_S_EZSIGNFOLDER_DESCRIPTION = "sEzsignfolderDescription";
  @SerializedName(SERIALIZED_NAME_S_EZSIGNFOLDER_DESCRIPTION)
  private String sEzsignfolderDescription;

  public static final String SERIALIZED_NAME_A_OBJ_FORM_DATA_DOCUMENT = "a_objFormDataDocument";
  @SerializedName(SERIALIZED_NAME_A_OBJ_FORM_DATA_DOCUMENT)
  private List<CustomFormDataDocumentResponse> aObjFormDataDocument = new ArrayList<>();

  public CustomFormsDataFolderResponse() {
  }

  public CustomFormsDataFolderResponse pkiEzsignfolderID(Integer pkiEzsignfolderID) {
    
    this.pkiEzsignfolderID = pkiEzsignfolderID;
    return this;
  }

   /**
   * The unique ID of the Ezsignfolder
   * minimum: 0
   * @return pkiEzsignfolderID
  **/
  @javax.annotation.Nonnull
  public Integer getPkiEzsignfolderID() {
    return pkiEzsignfolderID;
  }


  public void setPkiEzsignfolderID(Integer pkiEzsignfolderID) {
    this.pkiEzsignfolderID = pkiEzsignfolderID;
  }


  public CustomFormsDataFolderResponse sEzsignfolderDescription(String sEzsignfolderDescription) {
    
    this.sEzsignfolderDescription = sEzsignfolderDescription;
    return this;
  }

   /**
   * The description of the Ezsignfolder
   * @return sEzsignfolderDescription
  **/
  @javax.annotation.Nonnull
  public String getsEzsignfolderDescription() {
    return sEzsignfolderDescription;
  }


  public void setsEzsignfolderDescription(String sEzsignfolderDescription) {
    this.sEzsignfolderDescription = sEzsignfolderDescription;
  }


  public CustomFormsDataFolderResponse aObjFormDataDocument(List<CustomFormDataDocumentResponse> aObjFormDataDocument) {
    
    this.aObjFormDataDocument = aObjFormDataDocument;
    return this;
  }

  public CustomFormsDataFolderResponse addAObjFormDataDocumentItem(CustomFormDataDocumentResponse aObjFormDataDocumentItem) {
    if (this.aObjFormDataDocument == null) {
      this.aObjFormDataDocument = new ArrayList<>();
    }
    this.aObjFormDataDocument.add(aObjFormDataDocumentItem);
    return this;
  }

   /**
   * Get aObjFormDataDocument
   * @return aObjFormDataDocument
  **/
  @javax.annotation.Nonnull
  public List<CustomFormDataDocumentResponse> getaObjFormDataDocument() {
    return aObjFormDataDocument;
  }


  public void setaObjFormDataDocument(List<CustomFormDataDocumentResponse> aObjFormDataDocument) {
    this.aObjFormDataDocument = aObjFormDataDocument;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CustomFormsDataFolderResponse customFormsDataFolderResponse = (CustomFormsDataFolderResponse) o;
    return Objects.equals(this.pkiEzsignfolderID, customFormsDataFolderResponse.pkiEzsignfolderID) &&
        Objects.equals(this.sEzsignfolderDescription, customFormsDataFolderResponse.sEzsignfolderDescription) &&
        Objects.equals(this.aObjFormDataDocument, customFormsDataFolderResponse.aObjFormDataDocument);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pkiEzsignfolderID, sEzsignfolderDescription, aObjFormDataDocument);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CustomFormsDataFolderResponse {\n");
    sb.append("    pkiEzsignfolderID: ").append(toIndentedString(pkiEzsignfolderID)).append("\n");
    sb.append("    sEzsignfolderDescription: ").append(toIndentedString(sEzsignfolderDescription)).append("\n");
    sb.append("    aObjFormDataDocument: ").append(toIndentedString(aObjFormDataDocument)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("pkiEzsignfolderID");
    openapiFields.add("sEzsignfolderDescription");
    openapiFields.add("a_objFormDataDocument");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("pkiEzsignfolderID");
    openapiRequiredFields.add("sEzsignfolderDescription");
    openapiRequiredFields.add("a_objFormDataDocument");
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to CustomFormsDataFolderResponse
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!CustomFormsDataFolderResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in CustomFormsDataFolderResponse is not found in the empty JSON string", CustomFormsDataFolderResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!CustomFormsDataFolderResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `CustomFormsDataFolderResponse` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : CustomFormsDataFolderResponse.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("sEzsignfolderDescription").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `sEzsignfolderDescription` to be a primitive type in the JSON string but got `%s`", jsonObj.get("sEzsignfolderDescription").toString()));
      }
      // ensure the json data is an array
      if (!jsonObj.get("a_objFormDataDocument").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `a_objFormDataDocument` to be an array in the JSON string but got `%s`", jsonObj.get("a_objFormDataDocument").toString()));
      }

      JsonArray jsonArrayaObjFormDataDocument = jsonObj.getAsJsonArray("a_objFormDataDocument");
      // validate the required field `a_objFormDataDocument` (array)
      for (int i = 0; i < jsonArrayaObjFormDataDocument.size(); i++) {
        CustomFormDataDocumentResponse.validateJsonElement(jsonArrayaObjFormDataDocument.get(i));
      };
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CustomFormsDataFolderResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CustomFormsDataFolderResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CustomFormsDataFolderResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CustomFormsDataFolderResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<CustomFormsDataFolderResponse>() {
           @Override
           public void write(JsonWriter out, CustomFormsDataFolderResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CustomFormsDataFolderResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of CustomFormsDataFolderResponse given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of CustomFormsDataFolderResponse
  * @throws IOException if the JSON string is invalid with respect to CustomFormsDataFolderResponse
  */
  public static CustomFormsDataFolderResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CustomFormsDataFolderResponse.class);
  }

 /**
  * Convert an instance of CustomFormsDataFolderResponse to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

