/*
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.2.2
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ezmax.api.model;

import java.util.Objects;
import com.ezmax.api.model.EzdoctemplatefieldtypecategoryAutocompleteElementResponse;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import eZmaxAPI.JSON;

/**
 * Payload for POST /2/object/ezdoctemplatefieldtypecategory/getAutocomplete
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-02-05T21:55:04.724341195Z[Etc/UTC]", comments = "Generator version: 7.11.0")
public class EzdoctemplatefieldtypecategoryGetAutocompleteV2ResponseMPayload {
  public static final String SERIALIZED_NAME_A_OBJ_EZDOCTEMPLATEFIELDTYPECATEGORY = "a_objEzdoctemplatefieldtypecategory";
  @SerializedName(SERIALIZED_NAME_A_OBJ_EZDOCTEMPLATEFIELDTYPECATEGORY)
  @javax.annotation.Nonnull
  private List<EzdoctemplatefieldtypecategoryAutocompleteElementResponse> aObjEzdoctemplatefieldtypecategory = new ArrayList<>();

  public EzdoctemplatefieldtypecategoryGetAutocompleteV2ResponseMPayload() {
  }

  public EzdoctemplatefieldtypecategoryGetAutocompleteV2ResponseMPayload aObjEzdoctemplatefieldtypecategory(@javax.annotation.Nonnull List<EzdoctemplatefieldtypecategoryAutocompleteElementResponse> aObjEzdoctemplatefieldtypecategory) {
    this.aObjEzdoctemplatefieldtypecategory = aObjEzdoctemplatefieldtypecategory;
    return this;
  }

  public EzdoctemplatefieldtypecategoryGetAutocompleteV2ResponseMPayload addAObjEzdoctemplatefieldtypecategoryItem(EzdoctemplatefieldtypecategoryAutocompleteElementResponse aObjEzdoctemplatefieldtypecategoryItem) {
    if (this.aObjEzdoctemplatefieldtypecategory == null) {
      this.aObjEzdoctemplatefieldtypecategory = new ArrayList<>();
    }
    this.aObjEzdoctemplatefieldtypecategory.add(aObjEzdoctemplatefieldtypecategoryItem);
    return this;
  }

  /**
   * An array of Ezdoctemplatefieldtypecategory autocomplete element response.
   * @return aObjEzdoctemplatefieldtypecategory
   */
  @javax.annotation.Nonnull
  public List<EzdoctemplatefieldtypecategoryAutocompleteElementResponse> getaObjEzdoctemplatefieldtypecategory() {
    return aObjEzdoctemplatefieldtypecategory;
  }

  public void setaObjEzdoctemplatefieldtypecategory(@javax.annotation.Nonnull List<EzdoctemplatefieldtypecategoryAutocompleteElementResponse> aObjEzdoctemplatefieldtypecategory) {
    this.aObjEzdoctemplatefieldtypecategory = aObjEzdoctemplatefieldtypecategory;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EzdoctemplatefieldtypecategoryGetAutocompleteV2ResponseMPayload ezdoctemplatefieldtypecategoryGetAutocompleteV2ResponseMPayload = (EzdoctemplatefieldtypecategoryGetAutocompleteV2ResponseMPayload) o;
    return Objects.equals(this.aObjEzdoctemplatefieldtypecategory, ezdoctemplatefieldtypecategoryGetAutocompleteV2ResponseMPayload.aObjEzdoctemplatefieldtypecategory);
  }

  @Override
  public int hashCode() {
    return Objects.hash(aObjEzdoctemplatefieldtypecategory);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EzdoctemplatefieldtypecategoryGetAutocompleteV2ResponseMPayload {\n");
    sb.append("    aObjEzdoctemplatefieldtypecategory: ").append(toIndentedString(aObjEzdoctemplatefieldtypecategory)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("a_objEzdoctemplatefieldtypecategory");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("a_objEzdoctemplatefieldtypecategory");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to EzdoctemplatefieldtypecategoryGetAutocompleteV2ResponseMPayload
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!EzdoctemplatefieldtypecategoryGetAutocompleteV2ResponseMPayload.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in EzdoctemplatefieldtypecategoryGetAutocompleteV2ResponseMPayload is not found in the empty JSON string", EzdoctemplatefieldtypecategoryGetAutocompleteV2ResponseMPayload.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!EzdoctemplatefieldtypecategoryGetAutocompleteV2ResponseMPayload.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `EzdoctemplatefieldtypecategoryGetAutocompleteV2ResponseMPayload` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : EzdoctemplatefieldtypecategoryGetAutocompleteV2ResponseMPayload.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // ensure the json data is an array
      if (!jsonObj.get("a_objEzdoctemplatefieldtypecategory").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `a_objEzdoctemplatefieldtypecategory` to be an array in the JSON string but got `%s`", jsonObj.get("a_objEzdoctemplatefieldtypecategory").toString()));
      }

      JsonArray jsonArrayaObjEzdoctemplatefieldtypecategory = jsonObj.getAsJsonArray("a_objEzdoctemplatefieldtypecategory");
      // validate the required field `a_objEzdoctemplatefieldtypecategory` (array)
      for (int i = 0; i < jsonArrayaObjEzdoctemplatefieldtypecategory.size(); i++) {
        EzdoctemplatefieldtypecategoryAutocompleteElementResponse.validateJsonElement(jsonArrayaObjEzdoctemplatefieldtypecategory.get(i));
      };
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!EzdoctemplatefieldtypecategoryGetAutocompleteV2ResponseMPayload.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'EzdoctemplatefieldtypecategoryGetAutocompleteV2ResponseMPayload' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<EzdoctemplatefieldtypecategoryGetAutocompleteV2ResponseMPayload> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(EzdoctemplatefieldtypecategoryGetAutocompleteV2ResponseMPayload.class));

       return (TypeAdapter<T>) new TypeAdapter<EzdoctemplatefieldtypecategoryGetAutocompleteV2ResponseMPayload>() {
           @Override
           public void write(JsonWriter out, EzdoctemplatefieldtypecategoryGetAutocompleteV2ResponseMPayload value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public EzdoctemplatefieldtypecategoryGetAutocompleteV2ResponseMPayload read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of EzdoctemplatefieldtypecategoryGetAutocompleteV2ResponseMPayload given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of EzdoctemplatefieldtypecategoryGetAutocompleteV2ResponseMPayload
   * @throws IOException if the JSON string is invalid with respect to EzdoctemplatefieldtypecategoryGetAutocompleteV2ResponseMPayload
   */
  public static EzdoctemplatefieldtypecategoryGetAutocompleteV2ResponseMPayload fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, EzdoctemplatefieldtypecategoryGetAutocompleteV2ResponseMPayload.class);
  }

  /**
   * Convert an instance of EzdoctemplatefieldtypecategoryGetAutocompleteV2ResponseMPayload to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

