/*
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.3.1
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ezmax.api.model;

import java.util.Objects;
import com.ezmax.api.model.EzsignbulksendResponseCompoundV3;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import eZmaxAPI.JSON;

/**
 * Payload for GET /3/object/ezsignbulksend/{pkiEzsignbulksendID}
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-06-17T23:06:06.857063645Z[Etc/UTC]", comments = "Generator version: 7.23.0")
public class EzsignbulksendGetObjectV3ResponseMPayload {
  public static final String SERIALIZED_NAME_OBJ_EZSIGNBULKSEND = "objEzsignbulksend";
  @SerializedName(SERIALIZED_NAME_OBJ_EZSIGNBULKSEND)
  @javax.annotation.Nonnull
  private EzsignbulksendResponseCompoundV3 objEzsignbulksend;

  public EzsignbulksendGetObjectV3ResponseMPayload() {
  }

  public EzsignbulksendGetObjectV3ResponseMPayload objEzsignbulksend(@javax.annotation.Nonnull EzsignbulksendResponseCompoundV3 objEzsignbulksend) {
    this.objEzsignbulksend = objEzsignbulksend;
    return this;
  }

  /**
   * Get objEzsignbulksend
   * @return objEzsignbulksend
   */
  @javax.annotation.Nonnull
  public EzsignbulksendResponseCompoundV3 getObjEzsignbulksend() {
    return objEzsignbulksend;
  }

  public void setObjEzsignbulksend(@javax.annotation.Nonnull EzsignbulksendResponseCompoundV3 objEzsignbulksend) {
    this.objEzsignbulksend = objEzsignbulksend;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EzsignbulksendGetObjectV3ResponseMPayload ezsignbulksendGetObjectV3ResponseMPayload = (EzsignbulksendGetObjectV3ResponseMPayload) o;
    return Objects.equals(this.objEzsignbulksend, ezsignbulksendGetObjectV3ResponseMPayload.objEzsignbulksend);
  }

  @Override
  public int hashCode() {
    return Objects.hash(objEzsignbulksend);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EzsignbulksendGetObjectV3ResponseMPayload {\n");
    sb.append("    objEzsignbulksend: ").append(toIndentedString(objEzsignbulksend)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("objEzsignbulksend"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("objEzsignbulksend"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to EzsignbulksendGetObjectV3ResponseMPayload
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!EzsignbulksendGetObjectV3ResponseMPayload.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in EzsignbulksendGetObjectV3ResponseMPayload is not found in the empty JSON string", EzsignbulksendGetObjectV3ResponseMPayload.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!EzsignbulksendGetObjectV3ResponseMPayload.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `EzsignbulksendGetObjectV3ResponseMPayload` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : EzsignbulksendGetObjectV3ResponseMPayload.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the required field `objEzsignbulksend`
      EzsignbulksendResponseCompoundV3.validateJsonElement(jsonObj.get("objEzsignbulksend"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!EzsignbulksendGetObjectV3ResponseMPayload.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'EzsignbulksendGetObjectV3ResponseMPayload' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<EzsignbulksendGetObjectV3ResponseMPayload> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(EzsignbulksendGetObjectV3ResponseMPayload.class));

       return (TypeAdapter<T>) new TypeAdapter<EzsignbulksendGetObjectV3ResponseMPayload>() {
           @Override
           public void write(JsonWriter out, EzsignbulksendGetObjectV3ResponseMPayload value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public EzsignbulksendGetObjectV3ResponseMPayload read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of EzsignbulksendGetObjectV3ResponseMPayload given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of EzsignbulksendGetObjectV3ResponseMPayload
   * @throws IOException if the JSON string is invalid with respect to EzsignbulksendGetObjectV3ResponseMPayload
   */
  public static EzsignbulksendGetObjectV3ResponseMPayload fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, EzsignbulksendGetObjectV3ResponseMPayload.class);
  }

  /**
   * Convert an instance of EzsignbulksendGetObjectV3ResponseMPayload to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

