/*
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.1.10
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ezmax.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.ezmax.api.model.EzsigntemplateResponseCompound;
import com.ezmax.api.model.EzsigntemplatepackagemembershipResponse;
import com.ezmax.api.model.EzsigntemplatepackagemembershipResponseCompoundAllOf;
import com.ezmax.api.model.EzsigntemplatepackagesignermembershipResponseCompound;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import eZmaxAPI.JSON;

/**
 * A Ezsigntemplatepackagemembership Object
 */
@ApiModel(description = "A Ezsigntemplatepackagemembership Object")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-08-23T17:18:53.039017Z[Etc/UTC]")
public class EzsigntemplatepackagemembershipResponseCompound {
  public static final String SERIALIZED_NAME_PKI_EZSIGNTEMPLATEPACKAGEMEMBERSHIP_I_D = "pkiEzsigntemplatepackagemembershipID";
  @SerializedName(SERIALIZED_NAME_PKI_EZSIGNTEMPLATEPACKAGEMEMBERSHIP_I_D)
  private Integer pkiEzsigntemplatepackagemembershipID;

  public static final String SERIALIZED_NAME_FKI_EZSIGNTEMPLATEPACKAGE_I_D = "fkiEzsigntemplatepackageID";
  @SerializedName(SERIALIZED_NAME_FKI_EZSIGNTEMPLATEPACKAGE_I_D)
  private Integer fkiEzsigntemplatepackageID;

  public static final String SERIALIZED_NAME_FKI_EZSIGNTEMPLATE_I_D = "fkiEzsigntemplateID";
  @SerializedName(SERIALIZED_NAME_FKI_EZSIGNTEMPLATE_I_D)
  private Integer fkiEzsigntemplateID;

  public static final String SERIALIZED_NAME_I_EZSIGNTEMPLATEPACKAGEMEMBERSHIP_ORDER = "iEzsigntemplatepackagemembershipOrder";
  @SerializedName(SERIALIZED_NAME_I_EZSIGNTEMPLATEPACKAGEMEMBERSHIP_ORDER)
  private Integer iEzsigntemplatepackagemembershipOrder;

  public static final String SERIALIZED_NAME_OBJ_EZSIGNTEMPLATE = "objEzsigntemplate";
  @SerializedName(SERIALIZED_NAME_OBJ_EZSIGNTEMPLATE)
  private EzsigntemplateResponseCompound objEzsigntemplate;

  public static final String SERIALIZED_NAME_A_OBJ_EZSIGNTEMPLATEPACKAGESIGNERMEMBERSHIP = "a_objEzsigntemplatepackagesignermembership";
  @SerializedName(SERIALIZED_NAME_A_OBJ_EZSIGNTEMPLATEPACKAGESIGNERMEMBERSHIP)
  private List<EzsigntemplatepackagesignermembershipResponseCompound> aObjEzsigntemplatepackagesignermembership = new ArrayList<>();

  public EzsigntemplatepackagemembershipResponseCompound() { 
  }

  public EzsigntemplatepackagemembershipResponseCompound pkiEzsigntemplatepackagemembershipID(Integer pkiEzsigntemplatepackagemembershipID) {
    
    this.pkiEzsigntemplatepackagemembershipID = pkiEzsigntemplatepackagemembershipID;
    return this;
  }

   /**
   * The unique ID of the Ezsigntemplatepackagemembership
   * minimum: 0
   * @return pkiEzsigntemplatepackagemembershipID
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "194", required = true, value = "The unique ID of the Ezsigntemplatepackagemembership")

  public Integer getPkiEzsigntemplatepackagemembershipID() {
    return pkiEzsigntemplatepackagemembershipID;
  }


  public void setPkiEzsigntemplatepackagemembershipID(Integer pkiEzsigntemplatepackagemembershipID) {
    this.pkiEzsigntemplatepackagemembershipID = pkiEzsigntemplatepackagemembershipID;
  }


  public EzsigntemplatepackagemembershipResponseCompound fkiEzsigntemplatepackageID(Integer fkiEzsigntemplatepackageID) {
    
    this.fkiEzsigntemplatepackageID = fkiEzsigntemplatepackageID;
    return this;
  }

   /**
   * The unique ID of the Ezsigntemplatepackage
   * minimum: 0
   * @return fkiEzsigntemplatepackageID
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "99", required = true, value = "The unique ID of the Ezsigntemplatepackage")

  public Integer getFkiEzsigntemplatepackageID() {
    return fkiEzsigntemplatepackageID;
  }


  public void setFkiEzsigntemplatepackageID(Integer fkiEzsigntemplatepackageID) {
    this.fkiEzsigntemplatepackageID = fkiEzsigntemplatepackageID;
  }


  public EzsigntemplatepackagemembershipResponseCompound fkiEzsigntemplateID(Integer fkiEzsigntemplateID) {
    
    this.fkiEzsigntemplateID = fkiEzsigntemplateID;
    return this;
  }

   /**
   * The unique ID of the Ezsigntemplate
   * minimum: 0
   * @return fkiEzsigntemplateID
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "36", required = true, value = "The unique ID of the Ezsigntemplate")

  public Integer getFkiEzsigntemplateID() {
    return fkiEzsigntemplateID;
  }


  public void setFkiEzsigntemplateID(Integer fkiEzsigntemplateID) {
    this.fkiEzsigntemplateID = fkiEzsigntemplateID;
  }


  public EzsigntemplatepackagemembershipResponseCompound iEzsigntemplatepackagemembershipOrder(Integer iEzsigntemplatepackagemembershipOrder) {
    
    this.iEzsigntemplatepackagemembershipOrder = iEzsigntemplatepackagemembershipOrder;
    return this;
  }

   /**
   * The order in which the Ezsigntemplate will be imported when using an Ezsigntemplatepackage.
   * minimum: 1
   * @return iEzsigntemplatepackagemembershipOrder
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "1", required = true, value = "The order in which the Ezsigntemplate will be imported when using an Ezsigntemplatepackage.")

  public Integer getiEzsigntemplatepackagemembershipOrder() {
    return iEzsigntemplatepackagemembershipOrder;
  }


  public void setiEzsigntemplatepackagemembershipOrder(Integer iEzsigntemplatepackagemembershipOrder) {
    this.iEzsigntemplatepackagemembershipOrder = iEzsigntemplatepackagemembershipOrder;
  }


  public EzsigntemplatepackagemembershipResponseCompound objEzsigntemplate(EzsigntemplateResponseCompound objEzsigntemplate) {
    
    this.objEzsigntemplate = objEzsigntemplate;
    return this;
  }

   /**
   * Get objEzsigntemplate
   * @return objEzsigntemplate
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public EzsigntemplateResponseCompound getObjEzsigntemplate() {
    return objEzsigntemplate;
  }


  public void setObjEzsigntemplate(EzsigntemplateResponseCompound objEzsigntemplate) {
    this.objEzsigntemplate = objEzsigntemplate;
  }


  public EzsigntemplatepackagemembershipResponseCompound aObjEzsigntemplatepackagesignermembership(List<EzsigntemplatepackagesignermembershipResponseCompound> aObjEzsigntemplatepackagesignermembership) {
    
    this.aObjEzsigntemplatepackagesignermembership = aObjEzsigntemplatepackagesignermembership;
    return this;
  }

  public EzsigntemplatepackagemembershipResponseCompound addAObjEzsigntemplatepackagesignermembershipItem(EzsigntemplatepackagesignermembershipResponseCompound aObjEzsigntemplatepackagesignermembershipItem) {
    this.aObjEzsigntemplatepackagesignermembership.add(aObjEzsigntemplatepackagesignermembershipItem);
    return this;
  }

   /**
   * Get aObjEzsigntemplatepackagesignermembership
   * @return aObjEzsigntemplatepackagesignermembership
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public List<EzsigntemplatepackagesignermembershipResponseCompound> getaObjEzsigntemplatepackagesignermembership() {
    return aObjEzsigntemplatepackagesignermembership;
  }


  public void setaObjEzsigntemplatepackagesignermembership(List<EzsigntemplatepackagesignermembershipResponseCompound> aObjEzsigntemplatepackagesignermembership) {
    this.aObjEzsigntemplatepackagesignermembership = aObjEzsigntemplatepackagesignermembership;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EzsigntemplatepackagemembershipResponseCompound ezsigntemplatepackagemembershipResponseCompound = (EzsigntemplatepackagemembershipResponseCompound) o;
    return Objects.equals(this.pkiEzsigntemplatepackagemembershipID, ezsigntemplatepackagemembershipResponseCompound.pkiEzsigntemplatepackagemembershipID) &&
        Objects.equals(this.fkiEzsigntemplatepackageID, ezsigntemplatepackagemembershipResponseCompound.fkiEzsigntemplatepackageID) &&
        Objects.equals(this.fkiEzsigntemplateID, ezsigntemplatepackagemembershipResponseCompound.fkiEzsigntemplateID) &&
        Objects.equals(this.iEzsigntemplatepackagemembershipOrder, ezsigntemplatepackagemembershipResponseCompound.iEzsigntemplatepackagemembershipOrder) &&
        Objects.equals(this.objEzsigntemplate, ezsigntemplatepackagemembershipResponseCompound.objEzsigntemplate) &&
        Objects.equals(this.aObjEzsigntemplatepackagesignermembership, ezsigntemplatepackagemembershipResponseCompound.aObjEzsigntemplatepackagesignermembership);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pkiEzsigntemplatepackagemembershipID, fkiEzsigntemplatepackageID, fkiEzsigntemplateID, iEzsigntemplatepackagemembershipOrder, objEzsigntemplate, aObjEzsigntemplatepackagesignermembership);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EzsigntemplatepackagemembershipResponseCompound {\n");
    sb.append("    pkiEzsigntemplatepackagemembershipID: ").append(toIndentedString(pkiEzsigntemplatepackagemembershipID)).append("\n");
    sb.append("    fkiEzsigntemplatepackageID: ").append(toIndentedString(fkiEzsigntemplatepackageID)).append("\n");
    sb.append("    fkiEzsigntemplateID: ").append(toIndentedString(fkiEzsigntemplateID)).append("\n");
    sb.append("    iEzsigntemplatepackagemembershipOrder: ").append(toIndentedString(iEzsigntemplatepackagemembershipOrder)).append("\n");
    sb.append("    objEzsigntemplate: ").append(toIndentedString(objEzsigntemplate)).append("\n");
    sb.append("    aObjEzsigntemplatepackagesignermembership: ").append(toIndentedString(aObjEzsigntemplatepackagesignermembership)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("pkiEzsigntemplatepackagemembershipID");
    openapiFields.add("fkiEzsigntemplatepackageID");
    openapiFields.add("fkiEzsigntemplateID");
    openapiFields.add("iEzsigntemplatepackagemembershipOrder");
    openapiFields.add("objEzsigntemplate");
    openapiFields.add("a_objEzsigntemplatepackagesignermembership");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("pkiEzsigntemplatepackagemembershipID");
    openapiRequiredFields.add("fkiEzsigntemplatepackageID");
    openapiRequiredFields.add("fkiEzsigntemplateID");
    openapiRequiredFields.add("iEzsigntemplatepackagemembershipOrder");
    openapiRequiredFields.add("objEzsigntemplate");
    openapiRequiredFields.add("a_objEzsigntemplatepackagesignermembership");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to EzsigntemplatepackagemembershipResponseCompound
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (EzsigntemplatepackagemembershipResponseCompound.openapiRequiredFields.isEmpty()) {
          return;
        } else { // has required fields
          throw new IllegalArgumentException(String.format("The required field(s) %s in EzsigntemplatepackagemembershipResponseCompound is not found in the empty JSON string", EzsigntemplatepackagemembershipResponseCompound.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!EzsigntemplatepackagemembershipResponseCompound.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `EzsigntemplatepackagemembershipResponseCompound` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : EzsigntemplatepackagemembershipResponseCompound.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      // validate the optional field `objEzsigntemplate`
      if (jsonObj.getAsJsonObject("objEzsigntemplate") != null) {
        EzsigntemplateResponseCompound.validateJsonObject(jsonObj.getAsJsonObject("objEzsigntemplate"));
      }
      JsonArray jsonArrayaObjEzsigntemplatepackagesignermembership = jsonObj.getAsJsonArray("a_objEzsigntemplatepackagesignermembership");
      if (jsonArrayaObjEzsigntemplatepackagesignermembership != null) {
        // ensure the json data is an array
        if (!jsonObj.get("a_objEzsigntemplatepackagesignermembership").isJsonArray()) {
          throw new IllegalArgumentException(String.format("Expected the field `a_objEzsigntemplatepackagesignermembership` to be an array in the JSON string but got `%s`", jsonObj.get("a_objEzsigntemplatepackagesignermembership").toString()));
        }

        // validate the optional field `a_objEzsigntemplatepackagesignermembership` (array)
        for (int i = 0; i < jsonArrayaObjEzsigntemplatepackagesignermembership.size(); i++) {
          EzsigntemplatepackagesignermembershipResponseCompound.validateJsonObject(jsonArrayaObjEzsigntemplatepackagesignermembership.get(i).getAsJsonObject());
        };
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!EzsigntemplatepackagemembershipResponseCompound.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'EzsigntemplatepackagemembershipResponseCompound' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<EzsigntemplatepackagemembershipResponseCompound> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(EzsigntemplatepackagemembershipResponseCompound.class));

       return (TypeAdapter<T>) new TypeAdapter<EzsigntemplatepackagemembershipResponseCompound>() {
           @Override
           public void write(JsonWriter out, EzsigntemplatepackagemembershipResponseCompound value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public EzsigntemplatepackagemembershipResponseCompound read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of EzsigntemplatepackagemembershipResponseCompound given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of EzsigntemplatepackagemembershipResponseCompound
  * @throws IOException if the JSON string is invalid with respect to EzsigntemplatepackagemembershipResponseCompound
  */
  public static EzsigntemplatepackagemembershipResponseCompound fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, EzsigntemplatepackagemembershipResponseCompound.class);
  }

 /**
  * Convert an instance of EzsigntemplatepackagemembershipResponseCompound to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

