/*
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ezmax.api.model;

import java.util.Objects;
import java.util.Locale;
import com.ezmax.api.model.CustomImportEzsigntemplatepackageRelationRequest;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;

import eZmaxAPI.JSON;

/**
 * Request for POST /2/object/ezsignfolder/{pkiEzsignfolderID}/importEzsigntemplatepackage
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-10-19T04:31:05.740372915Z[Etc/UTC]", comments = "Generator version: 7.16.0")
public class EzsignfolderImportEzsigntemplatepackageV2Request {
  public static final String SERIALIZED_NAME_FKI_EZSIGNTEMPLATEPACKAGE_I_D = "fkiEzsigntemplatepackageID";
  @SerializedName(SERIALIZED_NAME_FKI_EZSIGNTEMPLATEPACKAGE_I_D)
  @javax.annotation.Nonnull
  private Integer fkiEzsigntemplatepackageID;

  public static final String SERIALIZED_NAME_DT_EZSIGNDOCUMENT_DUEDATE = "dtEzsigndocumentDuedate";
  @SerializedName(SERIALIZED_NAME_DT_EZSIGNDOCUMENT_DUEDATE)
  @javax.annotation.Nonnull
  private String dtEzsigndocumentDuedate;

  public static final String SERIALIZED_NAME_A_OBJ_IMPORT_EZSIGNTEMPLATEPACKAGE_RELATION = "a_objImportEzsigntemplatepackageRelation";
  @SerializedName(SERIALIZED_NAME_A_OBJ_IMPORT_EZSIGNTEMPLATEPACKAGE_RELATION)
  @javax.annotation.Nonnull
  private List<CustomImportEzsigntemplatepackageRelationRequest> aObjImportEzsigntemplatepackageRelation = new ArrayList<>();

  public EzsignfolderImportEzsigntemplatepackageV2Request() {
  }

  public EzsignfolderImportEzsigntemplatepackageV2Request fkiEzsigntemplatepackageID(@javax.annotation.Nonnull Integer fkiEzsigntemplatepackageID) {
    this.fkiEzsigntemplatepackageID = fkiEzsigntemplatepackageID;
    return this;
  }

  /**
   * The unique ID of the Ezsigntemplatepackage
   * minimum: 0
   * @return fkiEzsigntemplatepackageID
   */
  @javax.annotation.Nonnull
  public Integer getFkiEzsigntemplatepackageID() {
    return fkiEzsigntemplatepackageID;
  }

  public void setFkiEzsigntemplatepackageID(@javax.annotation.Nonnull Integer fkiEzsigntemplatepackageID) {
    this.fkiEzsigntemplatepackageID = fkiEzsigntemplatepackageID;
  }


  public EzsignfolderImportEzsigntemplatepackageV2Request dtEzsigndocumentDuedate(@javax.annotation.Nonnull String dtEzsigndocumentDuedate) {
    this.dtEzsigndocumentDuedate = dtEzsigndocumentDuedate;
    return this;
  }

  /**
   * The maximum date and time at which the Ezsigndocument can be signed.
   * @return dtEzsigndocumentDuedate
   */
  @javax.annotation.Nonnull
  public String getDtEzsigndocumentDuedate() {
    return dtEzsigndocumentDuedate;
  }

  public void setDtEzsigndocumentDuedate(@javax.annotation.Nonnull String dtEzsigndocumentDuedate) {
    this.dtEzsigndocumentDuedate = dtEzsigndocumentDuedate;
  }


  public EzsignfolderImportEzsigntemplatepackageV2Request aObjImportEzsigntemplatepackageRelation(@javax.annotation.Nonnull List<CustomImportEzsigntemplatepackageRelationRequest> aObjImportEzsigntemplatepackageRelation) {
    this.aObjImportEzsigntemplatepackageRelation = aObjImportEzsigntemplatepackageRelation;
    return this;
  }

  public EzsignfolderImportEzsigntemplatepackageV2Request addAObjImportEzsigntemplatepackageRelationItem(CustomImportEzsigntemplatepackageRelationRequest aObjImportEzsigntemplatepackageRelationItem) {
    if (this.aObjImportEzsigntemplatepackageRelation == null) {
      this.aObjImportEzsigntemplatepackageRelation = new ArrayList<>();
    }
    this.aObjImportEzsigntemplatepackageRelation.add(aObjImportEzsigntemplatepackageRelationItem);
    return this;
  }

  /**
   * Get aObjImportEzsigntemplatepackageRelation
   * @return aObjImportEzsigntemplatepackageRelation
   */
  @javax.annotation.Nonnull
  public List<CustomImportEzsigntemplatepackageRelationRequest> getaObjImportEzsigntemplatepackageRelation() {
    return aObjImportEzsigntemplatepackageRelation;
  }

  public void setaObjImportEzsigntemplatepackageRelation(@javax.annotation.Nonnull List<CustomImportEzsigntemplatepackageRelationRequest> aObjImportEzsigntemplatepackageRelation) {
    this.aObjImportEzsigntemplatepackageRelation = aObjImportEzsigntemplatepackageRelation;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EzsignfolderImportEzsigntemplatepackageV2Request ezsignfolderImportEzsigntemplatepackageV2Request = (EzsignfolderImportEzsigntemplatepackageV2Request) o;
    return Objects.equals(this.fkiEzsigntemplatepackageID, ezsignfolderImportEzsigntemplatepackageV2Request.fkiEzsigntemplatepackageID) &&
        Objects.equals(this.dtEzsigndocumentDuedate, ezsignfolderImportEzsigntemplatepackageV2Request.dtEzsigndocumentDuedate) &&
        Objects.equals(this.aObjImportEzsigntemplatepackageRelation, ezsignfolderImportEzsigntemplatepackageV2Request.aObjImportEzsigntemplatepackageRelation);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fkiEzsigntemplatepackageID, dtEzsigndocumentDuedate, aObjImportEzsigntemplatepackageRelation);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EzsignfolderImportEzsigntemplatepackageV2Request {\n");
    sb.append("    fkiEzsigntemplatepackageID: ").append(toIndentedString(fkiEzsigntemplatepackageID)).append("\n");
    sb.append("    dtEzsigndocumentDuedate: ").append(toIndentedString(dtEzsigndocumentDuedate)).append("\n");
    sb.append("    aObjImportEzsigntemplatepackageRelation: ").append(toIndentedString(aObjImportEzsigntemplatepackageRelation)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("fkiEzsigntemplatepackageID", "dtEzsigndocumentDuedate", "a_objImportEzsigntemplatepackageRelation"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("fkiEzsigntemplatepackageID", "dtEzsigndocumentDuedate", "a_objImportEzsigntemplatepackageRelation"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to EzsignfolderImportEzsigntemplatepackageV2Request
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!EzsignfolderImportEzsigntemplatepackageV2Request.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field(s) %s in EzsignfolderImportEzsigntemplatepackageV2Request is not found in the empty JSON string", EzsignfolderImportEzsigntemplatepackageV2Request.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!EzsignfolderImportEzsigntemplatepackageV2Request.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The field `%s` in the JSON string is not defined in the `EzsignfolderImportEzsigntemplatepackageV2Request` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : EzsignfolderImportEzsigntemplatepackageV2Request.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("dtEzsigndocumentDuedate").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `dtEzsigndocumentDuedate` to be a primitive type in the JSON string but got `%s`", jsonObj.get("dtEzsigndocumentDuedate").toString()));
      }
      // ensure the json data is an array
      if (!jsonObj.get("a_objImportEzsigntemplatepackageRelation").isJsonArray()) {
        throw new IllegalArgumentException(String.format(Locale.ROOT, "Expected the field `a_objImportEzsigntemplatepackageRelation` to be an array in the JSON string but got `%s`", jsonObj.get("a_objImportEzsigntemplatepackageRelation").toString()));
      }

      JsonArray jsonArrayaObjImportEzsigntemplatepackageRelation = jsonObj.getAsJsonArray("a_objImportEzsigntemplatepackageRelation");
      // validate the required field `a_objImportEzsigntemplatepackageRelation` (array)
      for (int i = 0; i < jsonArrayaObjImportEzsigntemplatepackageRelation.size(); i++) {
        CustomImportEzsigntemplatepackageRelationRequest.validateJsonElement(jsonArrayaObjImportEzsigntemplatepackageRelation.get(i));
      };
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!EzsignfolderImportEzsigntemplatepackageV2Request.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'EzsignfolderImportEzsigntemplatepackageV2Request' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<EzsignfolderImportEzsigntemplatepackageV2Request> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(EzsignfolderImportEzsigntemplatepackageV2Request.class));

       return (TypeAdapter<T>) new TypeAdapter<EzsignfolderImportEzsigntemplatepackageV2Request>() {
           @Override
           public void write(JsonWriter out, EzsignfolderImportEzsigntemplatepackageV2Request value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public EzsignfolderImportEzsigntemplatepackageV2Request read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of EzsignfolderImportEzsigntemplatepackageV2Request given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of EzsignfolderImportEzsigntemplatepackageV2Request
   * @throws IOException if the JSON string is invalid with respect to EzsignfolderImportEzsigntemplatepackageV2Request
   */
  public static EzsignfolderImportEzsigntemplatepackageV2Request fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, EzsignfolderImportEzsigntemplatepackageV2Request.class);
  }

  /**
   * Convert an instance of EzsignfolderImportEzsigntemplatepackageV2Request to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

