/*
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.2.2
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ezmax.api.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import eZmaxAPI.JSON;

/**
 * Payload for POST /3/object/ezsignfoldertype
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-02-04T21:44:04.165556308Z[Etc/UTC]", comments = "Generator version: 7.11.0")
public class EzsignfoldertypeCreateObjectV3ResponseMPayload {
  public static final String SERIALIZED_NAME_A_PKI_EZSIGNFOLDERTYPE_I_D = "a_pkiEzsignfoldertypeID";
  @SerializedName(SERIALIZED_NAME_A_PKI_EZSIGNFOLDERTYPE_I_D)
  @javax.annotation.Nonnull
  private List<Integer> aPkiEzsignfoldertypeID = new ArrayList<>();

  public EzsignfoldertypeCreateObjectV3ResponseMPayload() {
  }

  public EzsignfoldertypeCreateObjectV3ResponseMPayload aPkiEzsignfoldertypeID(@javax.annotation.Nonnull List<Integer> aPkiEzsignfoldertypeID) {
    this.aPkiEzsignfoldertypeID = aPkiEzsignfoldertypeID;
    return this;
  }

  public EzsignfoldertypeCreateObjectV3ResponseMPayload addAPkiEzsignfoldertypeIDItem(Integer aPkiEzsignfoldertypeIDItem) {
    if (this.aPkiEzsignfoldertypeID == null) {
      this.aPkiEzsignfoldertypeID = new ArrayList<>();
    }
    this.aPkiEzsignfoldertypeID.add(aPkiEzsignfoldertypeIDItem);
    return this;
  }

  /**
   * An array of unique IDs representing the object that were requested to be created.  They are returned in the same order as the array containing the objects to be created that was sent in the request.
   * @return aPkiEzsignfoldertypeID
   */
  @javax.annotation.Nonnull
  public List<Integer> getaPkiEzsignfoldertypeID() {
    return aPkiEzsignfoldertypeID;
  }

  public void setaPkiEzsignfoldertypeID(@javax.annotation.Nonnull List<Integer> aPkiEzsignfoldertypeID) {
    this.aPkiEzsignfoldertypeID = aPkiEzsignfoldertypeID;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EzsignfoldertypeCreateObjectV3ResponseMPayload ezsignfoldertypeCreateObjectV3ResponseMPayload = (EzsignfoldertypeCreateObjectV3ResponseMPayload) o;
    return Objects.equals(this.aPkiEzsignfoldertypeID, ezsignfoldertypeCreateObjectV3ResponseMPayload.aPkiEzsignfoldertypeID);
  }

  @Override
  public int hashCode() {
    return Objects.hash(aPkiEzsignfoldertypeID);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EzsignfoldertypeCreateObjectV3ResponseMPayload {\n");
    sb.append("    aPkiEzsignfoldertypeID: ").append(toIndentedString(aPkiEzsignfoldertypeID)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("a_pkiEzsignfoldertypeID");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("a_pkiEzsignfoldertypeID");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to EzsignfoldertypeCreateObjectV3ResponseMPayload
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!EzsignfoldertypeCreateObjectV3ResponseMPayload.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in EzsignfoldertypeCreateObjectV3ResponseMPayload is not found in the empty JSON string", EzsignfoldertypeCreateObjectV3ResponseMPayload.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!EzsignfoldertypeCreateObjectV3ResponseMPayload.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `EzsignfoldertypeCreateObjectV3ResponseMPayload` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : EzsignfoldertypeCreateObjectV3ResponseMPayload.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // ensure the required json array is present
      if (jsonObj.get("a_pkiEzsignfoldertypeID") == null) {
        throw new IllegalArgumentException("Expected the field `linkedContent` to be an array in the JSON string but got `null`");
      } else if (!jsonObj.get("a_pkiEzsignfoldertypeID").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `a_pkiEzsignfoldertypeID` to be an array in the JSON string but got `%s`", jsonObj.get("a_pkiEzsignfoldertypeID").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!EzsignfoldertypeCreateObjectV3ResponseMPayload.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'EzsignfoldertypeCreateObjectV3ResponseMPayload' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<EzsignfoldertypeCreateObjectV3ResponseMPayload> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(EzsignfoldertypeCreateObjectV3ResponseMPayload.class));

       return (TypeAdapter<T>) new TypeAdapter<EzsignfoldertypeCreateObjectV3ResponseMPayload>() {
           @Override
           public void write(JsonWriter out, EzsignfoldertypeCreateObjectV3ResponseMPayload value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public EzsignfoldertypeCreateObjectV3ResponseMPayload read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of EzsignfoldertypeCreateObjectV3ResponseMPayload given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of EzsignfoldertypeCreateObjectV3ResponseMPayload
   * @throws IOException if the JSON string is invalid with respect to EzsignfoldertypeCreateObjectV3ResponseMPayload
   */
  public static EzsignfoldertypeCreateObjectV3ResponseMPayload fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, EzsignfoldertypeCreateObjectV3ResponseMPayload.class);
  }

  /**
   * Convert an instance of EzsignfoldertypeCreateObjectV3ResponseMPayload to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

