/*
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.2.1
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ezmax.api.model;

import java.util.Objects;
import com.ezmax.api.model.CommonAudit;
import com.ezmax.api.model.ContactResponseCompound;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import eZmaxAPI.JSON;

/**
 * A Ezsignuser Object
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-01-16T21:39:53.290322577Z[Etc/UTC]", comments = "Generator version: 7.10.0")
public class EzsignuserResponseCompound {
  public static final String SERIALIZED_NAME_PKI_EZSIGNUSER_I_D = "pkiEzsignuserID";
  @SerializedName(SERIALIZED_NAME_PKI_EZSIGNUSER_I_D)
  @javax.annotation.Nonnull
  private Integer pkiEzsignuserID;

  public static final String SERIALIZED_NAME_FKI_CONTACT_I_D = "fkiContactID";
  @SerializedName(SERIALIZED_NAME_FKI_CONTACT_I_D)
  @javax.annotation.Nonnull
  private Integer fkiContactID;

  public static final String SERIALIZED_NAME_OBJ_CONTACT = "objContact";
  @SerializedName(SERIALIZED_NAME_OBJ_CONTACT)
  @javax.annotation.Nonnull
  private ContactResponseCompound objContact;

  public static final String SERIALIZED_NAME_OBJ_AUDIT = "objAudit";
  @SerializedName(SERIALIZED_NAME_OBJ_AUDIT)
  @javax.annotation.Nonnull
  private CommonAudit objAudit;

  public EzsignuserResponseCompound() {
  }

  public EzsignuserResponseCompound pkiEzsignuserID(@javax.annotation.Nonnull Integer pkiEzsignuserID) {
    this.pkiEzsignuserID = pkiEzsignuserID;
    return this;
  }

  /**
   * The unique ID of the Ezsignuser
   * minimum: 0
   * maximum: 65535
   * @return pkiEzsignuserID
   */
  @javax.annotation.Nonnull
  public Integer getPkiEzsignuserID() {
    return pkiEzsignuserID;
  }

  public void setPkiEzsignuserID(@javax.annotation.Nonnull Integer pkiEzsignuserID) {
    this.pkiEzsignuserID = pkiEzsignuserID;
  }


  public EzsignuserResponseCompound fkiContactID(@javax.annotation.Nonnull Integer fkiContactID) {
    this.fkiContactID = fkiContactID;
    return this;
  }

  /**
   * The unique ID of the Contact
   * minimum: 0
   * @return fkiContactID
   */
  @javax.annotation.Nonnull
  public Integer getFkiContactID() {
    return fkiContactID;
  }

  public void setFkiContactID(@javax.annotation.Nonnull Integer fkiContactID) {
    this.fkiContactID = fkiContactID;
  }


  public EzsignuserResponseCompound objContact(@javax.annotation.Nonnull ContactResponseCompound objContact) {
    this.objContact = objContact;
    return this;
  }

  /**
   * Get objContact
   * @return objContact
   */
  @javax.annotation.Nonnull
  public ContactResponseCompound getObjContact() {
    return objContact;
  }

  public void setObjContact(@javax.annotation.Nonnull ContactResponseCompound objContact) {
    this.objContact = objContact;
  }


  public EzsignuserResponseCompound objAudit(@javax.annotation.Nonnull CommonAudit objAudit) {
    this.objAudit = objAudit;
    return this;
  }

  /**
   * Get objAudit
   * @return objAudit
   */
  @javax.annotation.Nonnull
  public CommonAudit getObjAudit() {
    return objAudit;
  }

  public void setObjAudit(@javax.annotation.Nonnull CommonAudit objAudit) {
    this.objAudit = objAudit;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EzsignuserResponseCompound ezsignuserResponseCompound = (EzsignuserResponseCompound) o;
    return Objects.equals(this.pkiEzsignuserID, ezsignuserResponseCompound.pkiEzsignuserID) &&
        Objects.equals(this.fkiContactID, ezsignuserResponseCompound.fkiContactID) &&
        Objects.equals(this.objContact, ezsignuserResponseCompound.objContact) &&
        Objects.equals(this.objAudit, ezsignuserResponseCompound.objAudit);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pkiEzsignuserID, fkiContactID, objContact, objAudit);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EzsignuserResponseCompound {\n");
    sb.append("    pkiEzsignuserID: ").append(toIndentedString(pkiEzsignuserID)).append("\n");
    sb.append("    fkiContactID: ").append(toIndentedString(fkiContactID)).append("\n");
    sb.append("    objContact: ").append(toIndentedString(objContact)).append("\n");
    sb.append("    objAudit: ").append(toIndentedString(objAudit)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("pkiEzsignuserID");
    openapiFields.add("fkiContactID");
    openapiFields.add("objContact");
    openapiFields.add("objAudit");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("pkiEzsignuserID");
    openapiRequiredFields.add("fkiContactID");
    openapiRequiredFields.add("objContact");
    openapiRequiredFields.add("objAudit");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to EzsignuserResponseCompound
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!EzsignuserResponseCompound.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in EzsignuserResponseCompound is not found in the empty JSON string", EzsignuserResponseCompound.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!EzsignuserResponseCompound.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `EzsignuserResponseCompound` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : EzsignuserResponseCompound.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the required field `objContact`
      ContactResponseCompound.validateJsonElement(jsonObj.get("objContact"));
      // validate the required field `objAudit`
      CommonAudit.validateJsonElement(jsonObj.get("objAudit"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!EzsignuserResponseCompound.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'EzsignuserResponseCompound' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<EzsignuserResponseCompound> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(EzsignuserResponseCompound.class));

       return (TypeAdapter<T>) new TypeAdapter<EzsignuserResponseCompound>() {
           @Override
           public void write(JsonWriter out, EzsignuserResponseCompound value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public EzsignuserResponseCompound read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of EzsignuserResponseCompound given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of EzsignuserResponseCompound
   * @throws IOException if the JSON string is invalid with respect to EzsignuserResponseCompound
   */
  public static EzsignuserResponseCompound fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, EzsignuserResponseCompound.class);
  }

  /**
   * Convert an instance of EzsignuserResponseCompound to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

