/*
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.1.7
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ezmax.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.ezmax.api.model.EzsignbulksenddocumentmappingResponseCompound;
import com.ezmax.api.model.EzsigntemplateResponseCompound;
import com.ezmax.api.model.EzsigntemplatepackageResponseCompound;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import eZmaxAPI.JSON;

/**
 * Payload for GET /1/object/ezsignbulksenddocumentmapping/{pkiEzsignbulksenddocumentmappingID}
 */
@ApiModel(description = "Payload for GET /1/object/ezsignbulksenddocumentmapping/{pkiEzsignbulksenddocumentmappingID}")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-05-17T16:00:12.138084Z[Etc/UTC]")
public class EzsignbulksenddocumentmappingGetObjectV1ResponseMPayload {
  public static final String SERIALIZED_NAME_PKI_EZSIGNBULKSENDDOCUMENTMAPPING_I_D = "pkiEzsignbulksenddocumentmappingID";
  @SerializedName(SERIALIZED_NAME_PKI_EZSIGNBULKSENDDOCUMENTMAPPING_I_D)
  private Integer pkiEzsignbulksenddocumentmappingID;

  public static final String SERIALIZED_NAME_FKI_EZSIGNBULKSEND_I_D = "fkiEzsignbulksendID";
  @SerializedName(SERIALIZED_NAME_FKI_EZSIGNBULKSEND_I_D)
  private Integer fkiEzsignbulksendID;

  public static final String SERIALIZED_NAME_FKI_EZSIGNTEMPLATEPACKAGE_I_D = "fkiEzsigntemplatepackageID";
  @SerializedName(SERIALIZED_NAME_FKI_EZSIGNTEMPLATEPACKAGE_I_D)
  private Integer fkiEzsigntemplatepackageID;

  public static final String SERIALIZED_NAME_FKI_EZSIGNTEMPLATE_I_D = "fkiEzsigntemplateID";
  @SerializedName(SERIALIZED_NAME_FKI_EZSIGNTEMPLATE_I_D)
  private Integer fkiEzsigntemplateID;

  public static final String SERIALIZED_NAME_I_EZSIGNBULKSENDDOCUMENTMAPPING_ORDER = "iEzsignbulksenddocumentmappingOrder";
  @SerializedName(SERIALIZED_NAME_I_EZSIGNBULKSENDDOCUMENTMAPPING_ORDER)
  private Integer iEzsignbulksenddocumentmappingOrder;

  public static final String SERIALIZED_NAME_OBJ_EZSIGNTEMPLATE = "objEzsigntemplate";
  @SerializedName(SERIALIZED_NAME_OBJ_EZSIGNTEMPLATE)
  private EzsigntemplateResponseCompound objEzsigntemplate;

  public static final String SERIALIZED_NAME_OBJ_EZSIGNTEMPLATEPACKAGE = "objEzsigntemplatepackage";
  @SerializedName(SERIALIZED_NAME_OBJ_EZSIGNTEMPLATEPACKAGE)
  private EzsigntemplatepackageResponseCompound objEzsigntemplatepackage;

  public EzsignbulksenddocumentmappingGetObjectV1ResponseMPayload() { 
  }

  public EzsignbulksenddocumentmappingGetObjectV1ResponseMPayload pkiEzsignbulksenddocumentmappingID(Integer pkiEzsignbulksenddocumentmappingID) {
    
    this.pkiEzsignbulksenddocumentmappingID = pkiEzsignbulksenddocumentmappingID;
    return this;
  }

   /**
   * The unique ID of the Ezsignbulksenddocumentmapping.
   * @return pkiEzsignbulksenddocumentmappingID
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "48", required = true, value = "The unique ID of the Ezsignbulksenddocumentmapping.")

  public Integer getPkiEzsignbulksenddocumentmappingID() {
    return pkiEzsignbulksenddocumentmappingID;
  }


  public void setPkiEzsignbulksenddocumentmappingID(Integer pkiEzsignbulksenddocumentmappingID) {
    this.pkiEzsignbulksenddocumentmappingID = pkiEzsignbulksenddocumentmappingID;
  }


  public EzsignbulksenddocumentmappingGetObjectV1ResponseMPayload fkiEzsignbulksendID(Integer fkiEzsignbulksendID) {
    
    this.fkiEzsignbulksendID = fkiEzsignbulksendID;
    return this;
  }

   /**
   * The unique ID of the Ezsignbulksend
   * @return fkiEzsignbulksendID
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "8", required = true, value = "The unique ID of the Ezsignbulksend")

  public Integer getFkiEzsignbulksendID() {
    return fkiEzsignbulksendID;
  }


  public void setFkiEzsignbulksendID(Integer fkiEzsignbulksendID) {
    this.fkiEzsignbulksendID = fkiEzsignbulksendID;
  }


  public EzsignbulksenddocumentmappingGetObjectV1ResponseMPayload fkiEzsigntemplatepackageID(Integer fkiEzsigntemplatepackageID) {
    
    this.fkiEzsigntemplatepackageID = fkiEzsigntemplatepackageID;
    return this;
  }

   /**
   * The unique ID of the Ezsigntemplatepackage
   * @return fkiEzsigntemplatepackageID
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "99", value = "The unique ID of the Ezsigntemplatepackage")

  public Integer getFkiEzsigntemplatepackageID() {
    return fkiEzsigntemplatepackageID;
  }


  public void setFkiEzsigntemplatepackageID(Integer fkiEzsigntemplatepackageID) {
    this.fkiEzsigntemplatepackageID = fkiEzsigntemplatepackageID;
  }


  public EzsignbulksenddocumentmappingGetObjectV1ResponseMPayload fkiEzsigntemplateID(Integer fkiEzsigntemplateID) {
    
    this.fkiEzsigntemplateID = fkiEzsigntemplateID;
    return this;
  }

   /**
   * The unique ID of the Ezsigntemplate
   * @return fkiEzsigntemplateID
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "36", value = "The unique ID of the Ezsigntemplate")

  public Integer getFkiEzsigntemplateID() {
    return fkiEzsigntemplateID;
  }


  public void setFkiEzsigntemplateID(Integer fkiEzsigntemplateID) {
    this.fkiEzsigntemplateID = fkiEzsigntemplateID;
  }


  public EzsignbulksenddocumentmappingGetObjectV1ResponseMPayload iEzsignbulksenddocumentmappingOrder(Integer iEzsignbulksenddocumentmappingOrder) {
    
    this.iEzsignbulksenddocumentmappingOrder = iEzsignbulksenddocumentmappingOrder;
    return this;
  }

   /**
   * The order in which the Ezsigntemplate or Ezsigntemplatepackage will be presented to the signatory in the Ezsignfolder.
   * @return iEzsignbulksenddocumentmappingOrder
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "1", required = true, value = "The order in which the Ezsigntemplate or Ezsigntemplatepackage will be presented to the signatory in the Ezsignfolder.")

  public Integer getiEzsignbulksenddocumentmappingOrder() {
    return iEzsignbulksenddocumentmappingOrder;
  }


  public void setiEzsignbulksenddocumentmappingOrder(Integer iEzsignbulksenddocumentmappingOrder) {
    this.iEzsignbulksenddocumentmappingOrder = iEzsignbulksenddocumentmappingOrder;
  }


  public EzsignbulksenddocumentmappingGetObjectV1ResponseMPayload objEzsigntemplate(EzsigntemplateResponseCompound objEzsigntemplate) {
    
    this.objEzsigntemplate = objEzsigntemplate;
    return this;
  }

   /**
   * Get objEzsigntemplate
   * @return objEzsigntemplate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public EzsigntemplateResponseCompound getObjEzsigntemplate() {
    return objEzsigntemplate;
  }


  public void setObjEzsigntemplate(EzsigntemplateResponseCompound objEzsigntemplate) {
    this.objEzsigntemplate = objEzsigntemplate;
  }


  public EzsignbulksenddocumentmappingGetObjectV1ResponseMPayload objEzsigntemplatepackage(EzsigntemplatepackageResponseCompound objEzsigntemplatepackage) {
    
    this.objEzsigntemplatepackage = objEzsigntemplatepackage;
    return this;
  }

   /**
   * Get objEzsigntemplatepackage
   * @return objEzsigntemplatepackage
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public EzsigntemplatepackageResponseCompound getObjEzsigntemplatepackage() {
    return objEzsigntemplatepackage;
  }


  public void setObjEzsigntemplatepackage(EzsigntemplatepackageResponseCompound objEzsigntemplatepackage) {
    this.objEzsigntemplatepackage = objEzsigntemplatepackage;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EzsignbulksenddocumentmappingGetObjectV1ResponseMPayload ezsignbulksenddocumentmappingGetObjectV1ResponseMPayload = (EzsignbulksenddocumentmappingGetObjectV1ResponseMPayload) o;
    return Objects.equals(this.pkiEzsignbulksenddocumentmappingID, ezsignbulksenddocumentmappingGetObjectV1ResponseMPayload.pkiEzsignbulksenddocumentmappingID) &&
        Objects.equals(this.fkiEzsignbulksendID, ezsignbulksenddocumentmappingGetObjectV1ResponseMPayload.fkiEzsignbulksendID) &&
        Objects.equals(this.fkiEzsigntemplatepackageID, ezsignbulksenddocumentmappingGetObjectV1ResponseMPayload.fkiEzsigntemplatepackageID) &&
        Objects.equals(this.fkiEzsigntemplateID, ezsignbulksenddocumentmappingGetObjectV1ResponseMPayload.fkiEzsigntemplateID) &&
        Objects.equals(this.iEzsignbulksenddocumentmappingOrder, ezsignbulksenddocumentmappingGetObjectV1ResponseMPayload.iEzsignbulksenddocumentmappingOrder) &&
        Objects.equals(this.objEzsigntemplate, ezsignbulksenddocumentmappingGetObjectV1ResponseMPayload.objEzsigntemplate) &&
        Objects.equals(this.objEzsigntemplatepackage, ezsignbulksenddocumentmappingGetObjectV1ResponseMPayload.objEzsigntemplatepackage);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pkiEzsignbulksenddocumentmappingID, fkiEzsignbulksendID, fkiEzsigntemplatepackageID, fkiEzsigntemplateID, iEzsignbulksenddocumentmappingOrder, objEzsigntemplate, objEzsigntemplatepackage);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EzsignbulksenddocumentmappingGetObjectV1ResponseMPayload {\n");
    sb.append("    pkiEzsignbulksenddocumentmappingID: ").append(toIndentedString(pkiEzsignbulksenddocumentmappingID)).append("\n");
    sb.append("    fkiEzsignbulksendID: ").append(toIndentedString(fkiEzsignbulksendID)).append("\n");
    sb.append("    fkiEzsigntemplatepackageID: ").append(toIndentedString(fkiEzsigntemplatepackageID)).append("\n");
    sb.append("    fkiEzsigntemplateID: ").append(toIndentedString(fkiEzsigntemplateID)).append("\n");
    sb.append("    iEzsignbulksenddocumentmappingOrder: ").append(toIndentedString(iEzsignbulksenddocumentmappingOrder)).append("\n");
    sb.append("    objEzsigntemplate: ").append(toIndentedString(objEzsigntemplate)).append("\n");
    sb.append("    objEzsigntemplatepackage: ").append(toIndentedString(objEzsigntemplatepackage)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("pkiEzsignbulksenddocumentmappingID");
    openapiFields.add("fkiEzsignbulksendID");
    openapiFields.add("fkiEzsigntemplatepackageID");
    openapiFields.add("fkiEzsigntemplateID");
    openapiFields.add("iEzsignbulksenddocumentmappingOrder");
    openapiFields.add("objEzsigntemplate");
    openapiFields.add("objEzsigntemplatepackage");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("pkiEzsignbulksenddocumentmappingID");
    openapiRequiredFields.add("fkiEzsignbulksendID");
    openapiRequiredFields.add("iEzsignbulksenddocumentmappingOrder");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to EzsignbulksenddocumentmappingGetObjectV1ResponseMPayload
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (EzsignbulksenddocumentmappingGetObjectV1ResponseMPayload.openapiRequiredFields.isEmpty()) {
          return;
        } else { // has required fields
          throw new IllegalArgumentException(String.format("The required field(s) %s in EzsignbulksenddocumentmappingGetObjectV1ResponseMPayload is not found in the empty JSON string", EzsignbulksenddocumentmappingGetObjectV1ResponseMPayload.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!EzsignbulksenddocumentmappingGetObjectV1ResponseMPayload.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `EzsignbulksenddocumentmappingGetObjectV1ResponseMPayload` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : EzsignbulksenddocumentmappingGetObjectV1ResponseMPayload.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      // validate the optional field `objEzsigntemplate`
      if (jsonObj.getAsJsonObject("objEzsigntemplate") != null) {
        EzsigntemplateResponseCompound.validateJsonObject(jsonObj.getAsJsonObject("objEzsigntemplate"));
      }
      // validate the optional field `objEzsigntemplatepackage`
      if (jsonObj.getAsJsonObject("objEzsigntemplatepackage") != null) {
        EzsigntemplatepackageResponseCompound.validateJsonObject(jsonObj.getAsJsonObject("objEzsigntemplatepackage"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!EzsignbulksenddocumentmappingGetObjectV1ResponseMPayload.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'EzsignbulksenddocumentmappingGetObjectV1ResponseMPayload' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<EzsignbulksenddocumentmappingGetObjectV1ResponseMPayload> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(EzsignbulksenddocumentmappingGetObjectV1ResponseMPayload.class));

       return (TypeAdapter<T>) new TypeAdapter<EzsignbulksenddocumentmappingGetObjectV1ResponseMPayload>() {
           @Override
           public void write(JsonWriter out, EzsignbulksenddocumentmappingGetObjectV1ResponseMPayload value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public EzsignbulksenddocumentmappingGetObjectV1ResponseMPayload read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of EzsignbulksenddocumentmappingGetObjectV1ResponseMPayload given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of EzsignbulksenddocumentmappingGetObjectV1ResponseMPayload
  * @throws IOException if the JSON string is invalid with respect to EzsignbulksenddocumentmappingGetObjectV1ResponseMPayload
  */
  public static EzsignbulksenddocumentmappingGetObjectV1ResponseMPayload fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, EzsignbulksenddocumentmappingGetObjectV1ResponseMPayload.class);
  }

 /**
  * Convert an instance of EzsignbulksenddocumentmappingGetObjectV1ResponseMPayload to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

