/*
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.2.2
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ezmax.api.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * The Dependency requirement of the Ezsigntemplateformfield
 */
@JsonAdapter(FieldEEzsigntemplateformfieldDependencyrequirement.Adapter.class)
public enum FieldEEzsigntemplateformfieldDependencyrequirement {
  
  ALL_OF("AllOf"),
  
  ANY_OF("AnyOf");

  private String value;

  FieldEEzsigntemplateformfieldDependencyrequirement(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static FieldEEzsigntemplateformfieldDependencyrequirement fromValue(String value) {
    for (FieldEEzsigntemplateformfieldDependencyrequirement b : FieldEEzsigntemplateformfieldDependencyrequirement.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<FieldEEzsigntemplateformfieldDependencyrequirement> {
    @Override
    public void write(final JsonWriter jsonWriter, final FieldEEzsigntemplateformfieldDependencyrequirement enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public FieldEEzsigntemplateformfieldDependencyrequirement read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return FieldEEzsigntemplateformfieldDependencyrequirement.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    FieldEEzsigntemplateformfieldDependencyrequirement.fromValue(value);
  }
}

