/*
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.1.14
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ezmax.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.ezmax.api.model.MultilingualNotificationsubsectionName;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import eZmaxAPI.JSON;

/**
 * A Notificationsubsection Object
 */
@ApiModel(description = "A Notificationsubsection Object")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-11-01T21:58:46.009232Z[Etc/UTC]")
public class NotificationsubsectionResponse {
  public static final String SERIALIZED_NAME_PKI_NOTIFICATIONSUBSECTION_I_D = "pkiNotificationsubsectionID";
  @SerializedName(SERIALIZED_NAME_PKI_NOTIFICATIONSUBSECTION_I_D)
  private Integer pkiNotificationsubsectionID;

  public static final String SERIALIZED_NAME_FKI_NOTIFICATIONSECTION_I_D = "fkiNotificationsectionID";
  @SerializedName(SERIALIZED_NAME_FKI_NOTIFICATIONSECTION_I_D)
  private Integer fkiNotificationsectionID;

  public static final String SERIALIZED_NAME_OBJ_NOTIFICATIONSUBSECTION_NAME = "objNotificationsubsectionName";
  @SerializedName(SERIALIZED_NAME_OBJ_NOTIFICATIONSUBSECTION_NAME)
  private MultilingualNotificationsubsectionName objNotificationsubsectionName;

  public static final String SERIALIZED_NAME_S_NOTIFICATIONSECTION_NAME_X = "sNotificationsectionNameX";
  @SerializedName(SERIALIZED_NAME_S_NOTIFICATIONSECTION_NAME_X)
  private String sNotificationsectionNameX;

  public static final String SERIALIZED_NAME_S_NOTIFICATIONSUBSECTION_NAME_X = "sNotificationsubsectionNameX";
  @SerializedName(SERIALIZED_NAME_S_NOTIFICATIONSUBSECTION_NAME_X)
  private String sNotificationsubsectionNameX;

  public NotificationsubsectionResponse() { 
  }

  public NotificationsubsectionResponse pkiNotificationsubsectionID(Integer pkiNotificationsubsectionID) {
    
    this.pkiNotificationsubsectionID = pkiNotificationsubsectionID;
    return this;
  }

   /**
   * The unique ID of the Notificationsubsection
   * minimum: 0
   * @return pkiNotificationsubsectionID
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "3", required = true, value = "The unique ID of the Notificationsubsection")

  public Integer getPkiNotificationsubsectionID() {
    return pkiNotificationsubsectionID;
  }


  public void setPkiNotificationsubsectionID(Integer pkiNotificationsubsectionID) {
    this.pkiNotificationsubsectionID = pkiNotificationsubsectionID;
  }


  public NotificationsubsectionResponse fkiNotificationsectionID(Integer fkiNotificationsectionID) {
    
    this.fkiNotificationsectionID = fkiNotificationsectionID;
    return this;
  }

   /**
   * The unique ID of the Notificationsection
   * minimum: 0
   * @return fkiNotificationsectionID
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "1", required = true, value = "The unique ID of the Notificationsection")

  public Integer getFkiNotificationsectionID() {
    return fkiNotificationsectionID;
  }


  public void setFkiNotificationsectionID(Integer fkiNotificationsectionID) {
    this.fkiNotificationsectionID = fkiNotificationsectionID;
  }


  public NotificationsubsectionResponse objNotificationsubsectionName(MultilingualNotificationsubsectionName objNotificationsubsectionName) {
    
    this.objNotificationsubsectionName = objNotificationsubsectionName;
    return this;
  }

   /**
   * Get objNotificationsubsectionName
   * @return objNotificationsubsectionName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public MultilingualNotificationsubsectionName getObjNotificationsubsectionName() {
    return objNotificationsubsectionName;
  }


  public void setObjNotificationsubsectionName(MultilingualNotificationsubsectionName objNotificationsubsectionName) {
    this.objNotificationsubsectionName = objNotificationsubsectionName;
  }


  public NotificationsubsectionResponse sNotificationsectionNameX(String sNotificationsectionNameX) {
    
    this.sNotificationsectionNameX = sNotificationsectionNameX;
    return this;
  }

   /**
   * The name of the Notificationsection in the language of the requester
   * @return sNotificationsectionNameX
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Homepage", value = "The name of the Notificationsection in the language of the requester")

  public String getsNotificationsectionNameX() {
    return sNotificationsectionNameX;
  }


  public void setsNotificationsectionNameX(String sNotificationsectionNameX) {
    this.sNotificationsectionNameX = sNotificationsectionNameX;
  }


  public NotificationsubsectionResponse sNotificationsubsectionNameX(String sNotificationsubsectionNameX) {
    
    this.sNotificationsubsectionNameX = sNotificationsubsectionNameX;
    return this;
  }

   /**
   * The name of the Notificationsubsection in the language of the requester
   * @return sNotificationsubsectionNameX
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "Default", required = true, value = "The name of the Notificationsubsection in the language of the requester")

  public String getsNotificationsubsectionNameX() {
    return sNotificationsubsectionNameX;
  }


  public void setsNotificationsubsectionNameX(String sNotificationsubsectionNameX) {
    this.sNotificationsubsectionNameX = sNotificationsubsectionNameX;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NotificationsubsectionResponse notificationsubsectionResponse = (NotificationsubsectionResponse) o;
    return Objects.equals(this.pkiNotificationsubsectionID, notificationsubsectionResponse.pkiNotificationsubsectionID) &&
        Objects.equals(this.fkiNotificationsectionID, notificationsubsectionResponse.fkiNotificationsectionID) &&
        Objects.equals(this.objNotificationsubsectionName, notificationsubsectionResponse.objNotificationsubsectionName) &&
        Objects.equals(this.sNotificationsectionNameX, notificationsubsectionResponse.sNotificationsectionNameX) &&
        Objects.equals(this.sNotificationsubsectionNameX, notificationsubsectionResponse.sNotificationsubsectionNameX);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pkiNotificationsubsectionID, fkiNotificationsectionID, objNotificationsubsectionName, sNotificationsectionNameX, sNotificationsubsectionNameX);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NotificationsubsectionResponse {\n");
    sb.append("    pkiNotificationsubsectionID: ").append(toIndentedString(pkiNotificationsubsectionID)).append("\n");
    sb.append("    fkiNotificationsectionID: ").append(toIndentedString(fkiNotificationsectionID)).append("\n");
    sb.append("    objNotificationsubsectionName: ").append(toIndentedString(objNotificationsubsectionName)).append("\n");
    sb.append("    sNotificationsectionNameX: ").append(toIndentedString(sNotificationsectionNameX)).append("\n");
    sb.append("    sNotificationsubsectionNameX: ").append(toIndentedString(sNotificationsubsectionNameX)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("pkiNotificationsubsectionID");
    openapiFields.add("fkiNotificationsectionID");
    openapiFields.add("objNotificationsubsectionName");
    openapiFields.add("sNotificationsectionNameX");
    openapiFields.add("sNotificationsubsectionNameX");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("pkiNotificationsubsectionID");
    openapiRequiredFields.add("fkiNotificationsectionID");
    openapiRequiredFields.add("sNotificationsubsectionNameX");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to NotificationsubsectionResponse
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (NotificationsubsectionResponse.openapiRequiredFields.isEmpty()) {
          return;
        } else { // has required fields
          throw new IllegalArgumentException(String.format("The required field(s) %s in NotificationsubsectionResponse is not found in the empty JSON string", NotificationsubsectionResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!NotificationsubsectionResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `NotificationsubsectionResponse` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : NotificationsubsectionResponse.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      // validate the optional field `objNotificationsubsectionName`
      if (jsonObj.getAsJsonObject("objNotificationsubsectionName") != null) {
        MultilingualNotificationsubsectionName.validateJsonObject(jsonObj.getAsJsonObject("objNotificationsubsectionName"));
      }
      if (jsonObj.get("sNotificationsectionNameX") != null && !jsonObj.get("sNotificationsectionNameX").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `sNotificationsectionNameX` to be a primitive type in the JSON string but got `%s`", jsonObj.get("sNotificationsectionNameX").toString()));
      }
      if (jsonObj.get("sNotificationsubsectionNameX") != null && !jsonObj.get("sNotificationsubsectionNameX").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `sNotificationsubsectionNameX` to be a primitive type in the JSON string but got `%s`", jsonObj.get("sNotificationsubsectionNameX").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!NotificationsubsectionResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'NotificationsubsectionResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<NotificationsubsectionResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(NotificationsubsectionResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<NotificationsubsectionResponse>() {
           @Override
           public void write(JsonWriter out, NotificationsubsectionResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public NotificationsubsectionResponse read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of NotificationsubsectionResponse given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of NotificationsubsectionResponse
  * @throws IOException if the JSON string is invalid with respect to NotificationsubsectionResponse
  */
  public static NotificationsubsectionResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, NotificationsubsectionResponse.class);
  }

 /**
  * Convert an instance of NotificationsubsectionResponse to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

