/*
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ezmax.api.model;

import com.ezmax.api.model.ActivesessionResponseCompoundApikey;
import com.ezmax.api.model.ActivesessionResponseCompoundUser;
import com.ezmax.api.model.FieldEActivesessionOrigin;
import com.ezmax.api.model.FieldEActivesessionUsertype;
import com.ezmax.api.model.FieldEActivesessionWeekdaystart;
import com.ezmax.api.model.FieldEUserEzsignaccess;
import com.ezmax.api.model.FieldEUserEzsignprepaid;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ActivesessionResponseCompound
 */
public class ActivesessionResponseCompoundTest {
    private final ActivesessionResponseCompound model = new ActivesessionResponseCompound();

    /**
     * Model tests for ActivesessionResponseCompound
     */
    @Test
    public void testActivesessionResponseCompound() {
        // TODO: test ActivesessionResponseCompound
    }

    /**
     * Test the property 'eActivesessionUsertype'
     */
    @Test
    public void eActivesessionUsertypeTest() {
        // TODO: test eActivesessionUsertype
    }

    /**
     * Test the property 'eActivesessionOrigin'
     */
    @Test
    public void eActivesessionOriginTest() {
        // TODO: test eActivesessionOrigin
    }

    /**
     * Test the property 'eActivesessionWeekdaystart'
     */
    @Test
    public void eActivesessionWeekdaystartTest() {
        // TODO: test eActivesessionWeekdaystart
    }

    /**
     * Test the property 'fkiLanguageID'
     */
    @Test
    public void fkiLanguageIDTest() {
        // TODO: test fkiLanguageID
    }

    /**
     * Test the property 'sCompanyNameX'
     */
    @Test
    public void sCompanyNameXTest() {
        // TODO: test sCompanyNameX
    }

    /**
     * Test the property 'sDepartmentNameX'
     */
    @Test
    public void sDepartmentNameXTest() {
        // TODO: test sDepartmentNameX
    }

    /**
     * Test the property 'bActivesessionDebug'
     */
    @Test
    public void bActivesessionDebugTest() {
        // TODO: test bActivesessionDebug
    }

    /**
     * Test the property 'bActivesessionIssuperadmin'
     */
    @Test
    public void bActivesessionIssuperadminTest() {
        // TODO: test bActivesessionIssuperadmin
    }

    /**
     * Test the property 'pksCustomerCode'
     */
    @Test
    public void pksCustomerCodeTest() {
        // TODO: test pksCustomerCode
    }

    /**
     * Test the property 'fkiSystemconfigurationtypeID'
     */
    @Test
    public void fkiSystemconfigurationtypeIDTest() {
        // TODO: test fkiSystemconfigurationtypeID
    }

    /**
     * Test the property 'fkiSignatureID'
     */
    @Test
    public void fkiSignatureIDTest() {
        // TODO: test fkiSignatureID
    }

    /**
     * Test the property 'eUserEzsignaccess'
     */
    @Test
    public void eUserEzsignaccessTest() {
        // TODO: test eUserEzsignaccess
    }

    /**
     * Test the property 'eUserEzsignprepaid'
     */
    @Test
    public void eUserEzsignprepaidTest() {
        // TODO: test eUserEzsignprepaid
    }

    /**
     * Test the property 'dtUserEzsignprepaidexpiration'
     */
    @Test
    public void dtUserEzsignprepaidexpirationTest() {
        // TODO: test dtUserEzsignprepaidexpiration
    }

    /**
     * Test the property 'aPkiPermissionID'
     */
    @Test
    public void aPkiPermissionIDTest() {
        // TODO: test aPkiPermissionID
    }

    /**
     * Test the property 'objUserReal'
     */
    @Test
    public void objUserRealTest() {
        // TODO: test objUserReal
    }

    /**
     * Test the property 'objUserCloned'
     */
    @Test
    public void objUserClonedTest() {
        // TODO: test objUserCloned
    }

    /**
     * Test the property 'objApikey'
     */
    @Test
    public void objApikeyTest() {
        // TODO: test objApikey
    }

    /**
     * Test the property 'aEModuleInternalname'
     */
    @Test
    public void aEModuleInternalnameTest() {
        // TODO: test aEModuleInternalname
    }

}
