/*
 * eZmax API Definition
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.0.43
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ezmax.api.model;

import com.ezmax.api.model.AuthenticateAuthenticateV2ResponseMPayload;
import com.ezmax.api.model.CommonResponse;
import com.ezmax.api.model.CommonResponseObjDebug;
import com.ezmax.api.model.CommonResponseObjDebugPayload;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for AuthenticateAuthenticateV2Response
 */
public class AuthenticateAuthenticateV2ResponseTest {
    private final AuthenticateAuthenticateV2Response model = new AuthenticateAuthenticateV2Response();

    /**
     * Model tests for AuthenticateAuthenticateV2Response
     */
    @Test
    public void testAuthenticateAuthenticateV2Response() {
        // TODO: test AuthenticateAuthenticateV2Response
    }

    /**
     * Test the property 'objDebugPayload'
     */
    @Test
    public void objDebugPayloadTest() {
        // TODO: test objDebugPayload
    }

    /**
     * Test the property 'objDebug'
     */
    @Test
    public void objDebugTest() {
        // TODO: test objDebug
    }

}
