/*
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ezmax.api.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CountryAutocompleteElementResponse
 */
public class CountryAutocompleteElementResponseTest {
    private final CountryAutocompleteElementResponse model = new CountryAutocompleteElementResponse();

    /**
     * Model tests for CountryAutocompleteElementResponse
     */
    @Test
    public void testCountryAutocompleteElementResponse() {
        // TODO: test CountryAutocompleteElementResponse
    }

    /**
     * Test the property 'pkiCountryID'
     */
    @Test
    public void pkiCountryIDTest() {
        // TODO: test pkiCountryID
    }

    /**
     * Test the property 'sCountryNameX'
     */
    @Test
    public void sCountryNameXTest() {
        // TODO: test sCountryNameX
    }

    /**
     * Test the property 'sCountryShortname'
     */
    @Test
    public void sCountryShortnameTest() {
        // TODO: test sCountryShortname
    }

    /**
     * Test the property 'bCountryIsactive'
     */
    @Test
    public void bCountryIsactiveTest() {
        // TODO: test bCountryIsactive
    }

}
