/*
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.2.1
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ezmax.api.model;

import com.ezmax.api.model.CustomContactNameResponse;
import com.ezmax.api.model.EmailResponse;
import com.ezmax.api.model.PhoneResponseCompound;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CustomCommunicationrecipientsrecipientResponse
 */
public class CustomCommunicationrecipientsrecipientResponseTest {
    private final CustomCommunicationrecipientsrecipientResponse model = new CustomCommunicationrecipientsrecipientResponse();

    /**
     * Model tests for CustomCommunicationrecipientsrecipientResponse
     */
    @Test
    public void testCustomCommunicationrecipientsrecipientResponse() {
        // TODO: test CustomCommunicationrecipientsrecipientResponse
    }

    /**
     * Test the property 'fkiAgentID'
     */
    @Test
    public void fkiAgentIDTest() {
        // TODO: test fkiAgentID
    }

    /**
     * Test the property 'fkiBrokerID'
     */
    @Test
    public void fkiBrokerIDTest() {
        // TODO: test fkiBrokerID
    }

    /**
     * Test the property 'fkiContactID'
     */
    @Test
    public void fkiContactIDTest() {
        // TODO: test fkiContactID
    }

    /**
     * Test the property 'fkiCustomerID'
     */
    @Test
    public void fkiCustomerIDTest() {
        // TODO: test fkiCustomerID
    }

    /**
     * Test the property 'fkiEmployeeID'
     */
    @Test
    public void fkiEmployeeIDTest() {
        // TODO: test fkiEmployeeID
    }

    /**
     * Test the property 'fkiEzsignsignerID'
     */
    @Test
    public void fkiEzsignsignerIDTest() {
        // TODO: test fkiEzsignsignerID
    }

    /**
     * Test the property 'fkiFranchiseofficeID'
     */
    @Test
    public void fkiFranchiseofficeIDTest() {
        // TODO: test fkiFranchiseofficeID
    }

    /**
     * Test the property 'fkiUserID'
     */
    @Test
    public void fkiUserIDTest() {
        // TODO: test fkiUserID
    }

    /**
     * Test the property 'fkiAgentincorporationID'
     */
    @Test
    public void fkiAgentincorporationIDTest() {
        // TODO: test fkiAgentincorporationID
    }

    /**
     * Test the property 'fkiAssistantID'
     */
    @Test
    public void fkiAssistantIDTest() {
        // TODO: test fkiAssistantID
    }

    /**
     * Test the property 'fkiExternalbrokerID'
     */
    @Test
    public void fkiExternalbrokerIDTest() {
        // TODO: test fkiExternalbrokerID
    }

    /**
     * Test the property 'fkiEzcomagentID'
     */
    @Test
    public void fkiEzcomagentIDTest() {
        // TODO: test fkiEzcomagentID
    }

    /**
     * Test the property 'fkiNotaryID'
     */
    @Test
    public void fkiNotaryIDTest() {
        // TODO: test fkiNotaryID
    }

    /**
     * Test the property 'fkiRewardmemberID'
     */
    @Test
    public void fkiRewardmemberIDTest() {
        // TODO: test fkiRewardmemberID
    }

    /**
     * Test the property 'fkiSupplierID'
     */
    @Test
    public void fkiSupplierIDTest() {
        // TODO: test fkiSupplierID
    }

    /**
     * Test the property 'eCommunicationrecipientsrecipientObjecttype'
     */
    @Test
    public void eCommunicationrecipientsrecipientObjecttypeTest() {
        // TODO: test eCommunicationrecipientsrecipientObjecttype
    }

    /**
     * Test the property 'objContactName'
     */
    @Test
    public void objContactNameTest() {
        // TODO: test objContactName
    }

    /**
     * Test the property 'objEmail'
     */
    @Test
    public void objEmailTest() {
        // TODO: test objEmail
    }

    /**
     * Test the property 'objPhoneFax'
     */
    @Test
    public void objPhoneFaxTest() {
        // TODO: test objPhoneFax
    }

    /**
     * Test the property 'objPhoneSMS'
     */
    @Test
    public void objPhoneSMSTest() {
        // TODO: test objPhoneSMS
    }

}
