/*
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.2.1
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ezmax.api.model;

import com.ezmax.api.model.FieldEEzdoctemplatedocumentPrivacylevel;
import com.ezmax.api.model.MultilingualEzdoctemplatedocumentName;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for EzdoctemplatedocumentResponseCompound
 */
public class EzdoctemplatedocumentResponseCompoundTest {
    private final EzdoctemplatedocumentResponseCompound model = new EzdoctemplatedocumentResponseCompound();

    /**
     * Model tests for EzdoctemplatedocumentResponseCompound
     */
    @Test
    public void testEzdoctemplatedocumentResponseCompound() {
        // TODO: test EzdoctemplatedocumentResponseCompound
    }

    /**
     * Test the property 'pkiEzdoctemplatedocumentID'
     */
    @Test
    public void pkiEzdoctemplatedocumentIDTest() {
        // TODO: test pkiEzdoctemplatedocumentID
    }

    /**
     * Test the property 'fkiLanguageID'
     */
    @Test
    public void fkiLanguageIDTest() {
        // TODO: test fkiLanguageID
    }

    /**
     * Test the property 'fkiEzsignfoldertypeID'
     */
    @Test
    public void fkiEzsignfoldertypeIDTest() {
        // TODO: test fkiEzsignfoldertypeID
    }

    /**
     * Test the property 'fkiEzdoctemplatetypeID'
     */
    @Test
    public void fkiEzdoctemplatetypeIDTest() {
        // TODO: test fkiEzdoctemplatetypeID
    }

    /**
     * Test the property 'fkiEzdoctemplatefieldtypecategoryID'
     */
    @Test
    public void fkiEzdoctemplatefieldtypecategoryIDTest() {
        // TODO: test fkiEzdoctemplatefieldtypecategoryID
    }

    /**
     * Test the property 'eEzdoctemplatedocumentPrivacylevel'
     */
    @Test
    public void eEzdoctemplatedocumentPrivacylevelTest() {
        // TODO: test eEzdoctemplatedocumentPrivacylevel
    }

    /**
     * Test the property 'bEzdoctemplatedocumentIsactive'
     */
    @Test
    public void bEzdoctemplatedocumentIsactiveTest() {
        // TODO: test bEzdoctemplatedocumentIsactive
    }

    /**
     * Test the property 'objEzdoctemplatedocumentName'
     */
    @Test
    public void objEzdoctemplatedocumentNameTest() {
        // TODO: test objEzdoctemplatedocumentName
    }

    /**
     * Test the property 'sEzdoctemplatedocumentNameX'
     */
    @Test
    public void sEzdoctemplatedocumentNameXTest() {
        // TODO: test sEzdoctemplatedocumentNameX
    }

    /**
     * Test the property 'sEzsignfoldertypeNameX'
     */
    @Test
    public void sEzsignfoldertypeNameXTest() {
        // TODO: test sEzsignfoldertypeNameX
    }

    /**
     * Test the property 'sEzdoctemplatefieldtypecategoryDescriptionX'
     */
    @Test
    public void sEzdoctemplatefieldtypecategoryDescriptionXTest() {
        // TODO: test sEzdoctemplatefieldtypecategoryDescriptionX
    }

    /**
     * Test the property 'sEzdoctemplatetypeDescriptionX'
     */
    @Test
    public void sEzdoctemplatetypeDescriptionXTest() {
        // TODO: test sEzdoctemplatetypeDescriptionX
    }

}
