/*
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.2.1
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ezmax.api.model;

import com.ezmax.api.model.FieldEEzsigntemplatepublicLimittype;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for EzsigntemplatepublicRequestCompound
 */
public class EzsigntemplatepublicRequestCompoundTest {
    private final EzsigntemplatepublicRequestCompound model = new EzsigntemplatepublicRequestCompound();

    /**
     * Model tests for EzsigntemplatepublicRequestCompound
     */
    @Test
    public void testEzsigntemplatepublicRequestCompound() {
        // TODO: test EzsigntemplatepublicRequestCompound
    }

    /**
     * Test the property 'pkiEzsigntemplatepublicID'
     */
    @Test
    public void pkiEzsigntemplatepublicIDTest() {
        // TODO: test pkiEzsigntemplatepublicID
    }

    /**
     * Test the property 'fkiEzsignfoldertypeID'
     */
    @Test
    public void fkiEzsignfoldertypeIDTest() {
        // TODO: test fkiEzsignfoldertypeID
    }

    /**
     * Test the property 'fkiUserlogintypeID'
     */
    @Test
    public void fkiUserlogintypeIDTest() {
        // TODO: test fkiUserlogintypeID
    }

    /**
     * Test the property 'fkiEzsigntemplateID'
     */
    @Test
    public void fkiEzsigntemplateIDTest() {
        // TODO: test fkiEzsigntemplateID
    }

    /**
     * Test the property 'fkiEzsigntemplatepackageID'
     */
    @Test
    public void fkiEzsigntemplatepackageIDTest() {
        // TODO: test fkiEzsigntemplatepackageID
    }

    /**
     * Test the property 'sEzsigntemplatepublicDescription'
     */
    @Test
    public void sEzsigntemplatepublicDescriptionTest() {
        // TODO: test sEzsigntemplatepublicDescription
    }

    /**
     * Test the property 'bEzsigntemplatepublicIsactive'
     */
    @Test
    public void bEzsigntemplatepublicIsactiveTest() {
        // TODO: test bEzsigntemplatepublicIsactive
    }

    /**
     * Test the property 'tEzsigntemplatepublicNote'
     */
    @Test
    public void tEzsigntemplatepublicNoteTest() {
        // TODO: test tEzsigntemplatepublicNote
    }

    /**
     * Test the property 'eEzsigntemplatepublicLimittype'
     */
    @Test
    public void eEzsigntemplatepublicLimittypeTest() {
        // TODO: test eEzsigntemplatepublicLimittype
    }

    /**
     * Test the property 'iEzsigntemplatepublicLimit'
     */
    @Test
    public void iEzsigntemplatepublicLimitTest() {
        // TODO: test iEzsigntemplatepublicLimit
    }

}
