/*
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.1.9
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ezmax.api.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for EzsigndocumentRequest
 */
public class EzsigndocumentRequestTest {
    private final EzsigndocumentRequest model = new EzsigndocumentRequest();

    /**
     * Model tests for EzsigndocumentRequest
     */
    @Test
    public void testEzsigndocumentRequest() {
        // TODO: test EzsigndocumentRequest
    }

    /**
     * Test the property 'pkiEzsigndocumentID'
     */
    @Test
    public void pkiEzsigndocumentIDTest() {
        // TODO: test pkiEzsigndocumentID
    }

    /**
     * Test the property 'fkiEzsignfolderID'
     */
    @Test
    public void fkiEzsignfolderIDTest() {
        // TODO: test fkiEzsignfolderID
    }

    /**
     * Test the property 'fkiEzsigntemplateID'
     */
    @Test
    public void fkiEzsigntemplateIDTest() {
        // TODO: test fkiEzsigntemplateID
    }

    /**
     * Test the property 'fkiEzsignfoldersignerassociationID'
     */
    @Test
    public void fkiEzsignfoldersignerassociationIDTest() {
        // TODO: test fkiEzsignfoldersignerassociationID
    }

    /**
     * Test the property 'fkiLanguageID'
     */
    @Test
    public void fkiLanguageIDTest() {
        // TODO: test fkiLanguageID
    }

    /**
     * Test the property 'eEzsigndocumentSource'
     */
    @Test
    public void eEzsigndocumentSourceTest() {
        // TODO: test eEzsigndocumentSource
    }

    /**
     * Test the property 'eEzsigndocumentFormat'
     */
    @Test
    public void eEzsigndocumentFormatTest() {
        // TODO: test eEzsigndocumentFormat
    }

    /**
     * Test the property 'sEzsigndocumentBase64'
     */
    @Test
    public void sEzsigndocumentBase64Test() {
        // TODO: test sEzsigndocumentBase64
    }

    /**
     * Test the property 'sEzsigndocumentUrl'
     */
    @Test
    public void sEzsigndocumentUrlTest() {
        // TODO: test sEzsigndocumentUrl
    }

    /**
     * Test the property 'bEzsigndocumentForcerepair'
     */
    @Test
    public void bEzsigndocumentForcerepairTest() {
        // TODO: test bEzsigndocumentForcerepair
    }

    /**
     * Test the property 'sEzsigndocumentPassword'
     */
    @Test
    public void sEzsigndocumentPasswordTest() {
        // TODO: test sEzsigndocumentPassword
    }

    /**
     * Test the property 'eEzsigndocumentForm'
     */
    @Test
    public void eEzsigndocumentFormTest() {
        // TODO: test eEzsigndocumentForm
    }

    /**
     * Test the property 'dtEzsigndocumentDuedate'
     */
    @Test
    public void dtEzsigndocumentDuedateTest() {
        // TODO: test dtEzsigndocumentDuedate
    }

    /**
     * Test the property 'sEzsigndocumentName'
     */
    @Test
    public void sEzsigndocumentNameTest() {
        // TODO: test sEzsigndocumentName
    }

}
