/*
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.2.1
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ezmax.api.model;

import com.ezmax.api.model.DiscussionRequest;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for EzsigndiscussionRequest
 */
public class EzsigndiscussionRequestTest {
    private final EzsigndiscussionRequest model = new EzsigndiscussionRequest();

    /**
     * Model tests for EzsigndiscussionRequest
     */
    @Test
    public void testEzsigndiscussionRequest() {
        // TODO: test EzsigndiscussionRequest
    }

    /**
     * Test the property 'pkiEzsigndiscussionID'
     */
    @Test
    public void pkiEzsigndiscussionIDTest() {
        // TODO: test pkiEzsigndiscussionID
    }

    /**
     * Test the property 'fkiEzsigndocumentID'
     */
    @Test
    public void fkiEzsigndocumentIDTest() {
        // TODO: test fkiEzsigndocumentID
    }

    /**
     * Test the property 'iEzsigndiscussionPagenumber'
     */
    @Test
    public void iEzsigndiscussionPagenumberTest() {
        // TODO: test iEzsigndiscussionPagenumber
    }

    /**
     * Test the property 'iEzsigndiscussionX'
     */
    @Test
    public void iEzsigndiscussionXTest() {
        // TODO: test iEzsigndiscussionX
    }

    /**
     * Test the property 'iEzsigndiscussionY'
     */
    @Test
    public void iEzsigndiscussionYTest() {
        // TODO: test iEzsigndiscussionY
    }

    /**
     * Test the property 'objDiscussion'
     */
    @Test
    public void objDiscussionTest() {
        // TODO: test objDiscussion
    }

}
