/*
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.1.17
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ezmax.api.model;

import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for FieldECommunicationEmailimportance
 */
public class FieldECommunicationEmailimportanceTest {
    /**
     * Model tests for FieldECommunicationEmailimportance
     */
    @Test
    public void testFieldECommunicationEmailimportance() {
        // TODO: test FieldECommunicationEmailimportance
    }

}
