/*
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.2.1
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ezmax.api.model;

import com.ezmax.api.model.GlaccountAutocompleteElementResponse;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GlaccountGetAutocompleteV2ResponseMPayload
 */
public class GlaccountGetAutocompleteV2ResponseMPayloadTest {
    private final GlaccountGetAutocompleteV2ResponseMPayload model = new GlaccountGetAutocompleteV2ResponseMPayload();

    /**
     * Model tests for GlaccountGetAutocompleteV2ResponseMPayload
     */
    @Test
    public void testGlaccountGetAutocompleteV2ResponseMPayload() {
        // TODO: test GlaccountGetAutocompleteV2ResponseMPayload
    }

    /**
     * Test the property 'aObjGlaccount'
     */
    @Test
    public void aObjGlaccountTest() {
        // TODO: test aObjGlaccount
    }

}
