/*
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.1.16
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ezmax.api.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for MultilingualEzmaxinvoicingsummaryinternalDescription
 */
public class MultilingualEzmaxinvoicingsummaryinternalDescriptionTest {
    private final MultilingualEzmaxinvoicingsummaryinternalDescription model = new MultilingualEzmaxinvoicingsummaryinternalDescription();

    /**
     * Model tests for MultilingualEzmaxinvoicingsummaryinternalDescription
     */
    @Test
    public void testMultilingualEzmaxinvoicingsummaryinternalDescription() {
        // TODO: test MultilingualEzmaxinvoicingsummaryinternalDescription
    }

    /**
     * Test the property 'sEzmaxinvoicingsummaryinternalDescription1'
     */
    @Test
    public void sEzmaxinvoicingsummaryinternalDescription1Test() {
        // TODO: test sEzmaxinvoicingsummaryinternalDescription1
    }

    /**
     * Test the property 'sEzmaxinvoicingsummaryinternalDescription2'
     */
    @Test
    public void sEzmaxinvoicingsummaryinternalDescription2Test() {
        // TODO: test sEzmaxinvoicingsummaryinternalDescription2
    }

}
