/*
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.1.17
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ezmax.api.model;

import com.ezmax.api.model.FieldESessionhistoryEndby;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for SessionhistoryListElement
 */
public class SessionhistoryListElementTest {
    private final SessionhistoryListElement model = new SessionhistoryListElement();

    /**
     * Model tests for SessionhistoryListElement
     */
    @Test
    public void testSessionhistoryListElement() {
        // TODO: test SessionhistoryListElement
    }

    /**
     * Test the property 'pkiSessionhistoryID'
     */
    @Test
    public void pkiSessionhistoryIDTest() {
        // TODO: test pkiSessionhistoryID
    }

    /**
     * Test the property 'fkiComputerID'
     */
    @Test
    public void fkiComputerIDTest() {
        // TODO: test fkiComputerID
    }

    /**
     * Test the property 'fkiUserID'
     */
    @Test
    public void fkiUserIDTest() {
        // TODO: test fkiUserID
    }

    /**
     * Test the property 'dtSessionhistoryFirsthit'
     */
    @Test
    public void dtSessionhistoryFirsthitTest() {
        // TODO: test dtSessionhistoryFirsthit
    }

    /**
     * Test the property 'dtSessionhistoryLasthit'
     */
    @Test
    public void dtSessionhistoryLasthitTest() {
        // TODO: test dtSessionhistoryLasthit
    }

    /**
     * Test the property 'eSessionhistoryEndby'
     */
    @Test
    public void eSessionhistoryEndbyTest() {
        // TODO: test eSessionhistoryEndby
    }

    /**
     * Test the property 'sComputerDescription'
     */
    @Test
    public void sComputerDescriptionTest() {
        // TODO: test sComputerDescription
    }

    /**
     * Test the property 'sSessionhistoryDuration'
     */
    @Test
    public void sSessionhistoryDurationTest() {
        // TODO: test sSessionhistoryDuration
    }

    /**
     * Test the property 'sSessionhistoryIP'
     */
    @Test
    public void sSessionhistoryIPTest() {
        // TODO: test sSessionhistoryIP
    }

    /**
     * Test the property 'sUserLoginname'
     */
    @Test
    public void sUserLoginnameTest() {
        // TODO: test sUserLoginname
    }

}
