/*
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.2.1
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ezmax.api.model;

import com.ezmax.api.model.SubnetResponseCompound;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SubnetGetObjectV2ResponseMPayload
 */
public class SubnetGetObjectV2ResponseMPayloadTest {
    private final SubnetGetObjectV2ResponseMPayload model = new SubnetGetObjectV2ResponseMPayload();

    /**
     * Model tests for SubnetGetObjectV2ResponseMPayload
     */
    @Test
    public void testSubnetGetObjectV2ResponseMPayload() {
        // TODO: test SubnetGetObjectV2ResponseMPayload
    }

    /**
     * Test the property 'objSubnet'
     */
    @Test
    public void objSubnetTest() {
        // TODO: test objSubnet
    }

}
