/*
 * eZmax API Definition
 * This API expose all the functionnalities for the eZmax and eZsign application.
 *
 * The version of the OpenAPI document: 1.0.30
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ezmax.api.model;

import com.ezmax.api.model.CommonAudit;
import com.ezmax.api.model.FieldEUserType;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for UserResponseAllOf
 */
public class UserResponseAllOfTest {
    private final UserResponseAllOf model = new UserResponseAllOf();

    /**
     * Model tests for UserResponseAllOf
     */
    @Test
    public void testUserResponseAllOf() {
        // TODO: test UserResponseAllOf
    }

    /**
     * Test the property 'pkiUserID'
     */
    @Test
    public void pkiUserIDTest() {
        // TODO: test pkiUserID
    }

    /**
     * Test the property 'fkiLanguageID'
     */
    @Test
    public void fkiLanguageIDTest() {
        // TODO: test fkiLanguageID
    }

    /**
     * Test the property 'eUserType'
     */
    @Test
    public void eUserTypeTest() {
        // TODO: test eUserType
    }

    /**
     * Test the property 'sUserFirstname'
     */
    @Test
    public void sUserFirstnameTest() {
        // TODO: test sUserFirstname
    }

    /**
     * Test the property 'sUserLastname'
     */
    @Test
    public void sUserLastnameTest() {
        // TODO: test sUserLastname
    }

    /**
     * Test the property 'sUserLoginname'
     */
    @Test
    public void sUserLoginnameTest() {
        // TODO: test sUserLoginname
    }

    /**
     * Test the property 'objAudit'
     */
    @Test
    public void objAuditTest() {
        // TODO: test objAudit
    }

}
