/*
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.2.1
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ezmax.api.model;

import com.ezmax.api.model.UserResponseCompound;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for UserGetObjectV2ResponseMPayload
 */
public class UserGetObjectV2ResponseMPayloadTest {
    private final UserGetObjectV2ResponseMPayload model = new UserGetObjectV2ResponseMPayload();

    /**
     * Model tests for UserGetObjectV2ResponseMPayload
     */
    @Test
    public void testUserGetObjectV2ResponseMPayload() {
        // TODO: test UserGetObjectV2ResponseMPayload
    }

    /**
     * Test the property 'objUser'
     */
    @Test
    public void objUserTest() {
        // TODO: test objUser
    }

}
