/*
 * eZmax API Definition (Full)
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.1.15
 * Contact: support-api@ezmax.ca
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ezmax.api.model;

import com.ezmax.api.model.WebhookGetObjectV2ResponseMPayload;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for WebhookGetObjectV2ResponseAllOf
 */
public class WebhookGetObjectV2ResponseAllOfTest {
    private final WebhookGetObjectV2ResponseAllOf model = new WebhookGetObjectV2ResponseAllOf();

    /**
     * Model tests for WebhookGetObjectV2ResponseAllOf
     */
    @Test
    public void testWebhookGetObjectV2ResponseAllOf() {
        // TODO: test WebhookGetObjectV2ResponseAllOf
    }

    /**
     * Test the property 'mPayload'
     */
    @Test
    public void mPayloadTest() {
        // TODO: test mPayload
    }

}
